/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.audit_dict.tables.records;


import com.tengzhe.jooq.data.audit_dict.tables.SystemProperty;

import java.util.Date;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemPropertyRecord extends UpdatableRecordImpl<SystemPropertyRecord> implements Record9<Long, Long, String, String, String, Integer, String, Date, Date> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>audit_dict.system_property.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>audit_dict.system_property.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>audit_dict.system_property.name</code>.
     */
    public void setName(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>audit_dict.system_property.name</code>.
     */
    public Long getName() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>audit_dict.system_property.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>audit_dict.system_property.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>audit_dict.system_property.label</code>.
     */
    public void setLabel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>audit_dict.system_property.label</code>.
     */
    public String getLabel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>audit_dict.system_property.group</code>.
     */
    public void setGroup(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>audit_dict.system_property.group</code>.
     */
    public String getGroup() {
        return (String) get(4);
    }

    /**
     * Setter for <code>audit_dict.system_property.enable</code>.
     */
    public void setEnable(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>audit_dict.system_property.enable</code>.
     */
    public Integer getEnable() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>audit_dict.system_property.remark</code>.
     */
    public void setRemark(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>audit_dict.system_property.remark</code>.
     */
    public String getRemark() {
        return (String) get(6);
    }

    /**
     * Setter for <code>audit_dict.system_property.create_time</code>.
     */
    public void setCreateTime(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>audit_dict.system_property.create_time</code>.
     */
    public Date getCreateTime() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>audit_dict.system_property.modify_time</code>.
     */
    public void setModifyTime(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>audit_dict.system_property.modify_time</code>.
     */
    public Date getModifyTime() {
        return (Date) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, String, String, String, Integer, String, Date, Date> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Long, String, String, String, Integer, String, Date, Date> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SystemProperty.SYSTEM_PROPERTY.ID;
    }

    @Override
    public Field<Long> field2() {
        return SystemProperty.SYSTEM_PROPERTY.NAME;
    }

    @Override
    public Field<String> field3() {
        return SystemProperty.SYSTEM_PROPERTY.VALUE;
    }

    @Override
    public Field<String> field4() {
        return SystemProperty.SYSTEM_PROPERTY.LABEL;
    }

    @Override
    public Field<String> field5() {
        return SystemProperty.SYSTEM_PROPERTY.GROUP;
    }

    @Override
    public Field<Integer> field6() {
        return SystemProperty.SYSTEM_PROPERTY.ENABLE;
    }

    @Override
    public Field<String> field7() {
        return SystemProperty.SYSTEM_PROPERTY.REMARK;
    }

    @Override
    public Field<Date> field8() {
        return SystemProperty.SYSTEM_PROPERTY.CREATE_TIME;
    }

    @Override
    public Field<Date> field9() {
        return SystemProperty.SYSTEM_PROPERTY.MODIFY_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getValue();
    }

    @Override
    public String component4() {
        return getLabel();
    }

    @Override
    public String component5() {
        return getGroup();
    }

    @Override
    public Integer component6() {
        return getEnable();
    }

    @Override
    public String component7() {
        return getRemark();
    }

    @Override
    public Date component8() {
        return getCreateTime();
    }

    @Override
    public Date component9() {
        return getModifyTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getValue();
    }

    @Override
    public String value4() {
        return getLabel();
    }

    @Override
    public String value5() {
        return getGroup();
    }

    @Override
    public Integer value6() {
        return getEnable();
    }

    @Override
    public String value7() {
        return getRemark();
    }

    @Override
    public Date value8() {
        return getCreateTime();
    }

    @Override
    public Date value9() {
        return getModifyTime();
    }

    @Override
    public SystemPropertyRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SystemPropertyRecord value2(Long value) {
        setName(value);
        return this;
    }

    @Override
    public SystemPropertyRecord value3(String value) {
        setValue(value);
        return this;
    }

    @Override
    public SystemPropertyRecord value4(String value) {
        setLabel(value);
        return this;
    }

    @Override
    public SystemPropertyRecord value5(String value) {
        setGroup(value);
        return this;
    }

    @Override
    public SystemPropertyRecord value6(Integer value) {
        setEnable(value);
        return this;
    }

    @Override
    public SystemPropertyRecord value7(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public SystemPropertyRecord value8(Date value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public SystemPropertyRecord value9(Date value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public SystemPropertyRecord values(Long value1, Long value2, String value3, String value4, String value5, Integer value6, String value7, Date value8, Date value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SystemPropertyRecord
     */
    public SystemPropertyRecord() {
        super(SystemProperty.SYSTEM_PROPERTY);
    }

    /**
     * Create a detached, initialised SystemPropertyRecord
     */
    public SystemPropertyRecord(Long id, Long name, String value, String label, String group, Integer enable, String remark, Date createTime, Date modifyTime) {
        super(SystemProperty.SYSTEM_PROPERTY);

        setId(id);
        setName(name);
        setValue(value);
        setLabel(label);
        setGroup(group);
        setEnable(enable);
        setRemark(remark);
        setCreateTime(createTime);
        setModifyTime(modifyTime);
    }
}
