/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.material.tables.records;


import com.tengzhe.jooq.data.material.tables.AuditRuleMeta;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuditRuleMetaRecord extends UpdatableRecordImpl<AuditRuleMetaRecord> implements Record11<Long, Integer, String, String, String, Integer, Integer, Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>material.audit_rule_meta.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>material.audit_rule_meta.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>material.audit_rule_meta.entity_type</code>.
     */
    public void setEntityType(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>material.audit_rule_meta.entity_type</code>.
     */
    public Integer getEntityType() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>material.audit_rule_meta.field</code>.
     */
    public void setField(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>material.audit_rule_meta.field</code>.
     */
    public String getField() {
        return (String) get(2);
    }

    /**
     * Setter for <code>material.audit_rule_meta.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>material.audit_rule_meta.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>material.audit_rule_meta.fact_field</code>.
     */
    public void setFactField(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>material.audit_rule_meta.fact_field</code>.
     */
    public String getFactField() {
        return (String) get(4);
    }

    /**
     * Setter for <code>material.audit_rule_meta.fact_multiple</code>.
     */
    public void setFactMultiple(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>material.audit_rule_meta.fact_multiple</code>.
     */
    public Integer getFactMultiple() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>material.audit_rule_meta.field_type</code>.
     */
    public void setFieldType(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>material.audit_rule_meta.field_type</code>.
     */
    public Integer getFieldType() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>material.audit_rule_meta.state</code>.
     */
    public void setState(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>material.audit_rule_meta.state</code>.
     */
    public Integer getState() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>material.audit_rule_meta.operator</code>.
     */
    public void setOperator(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>material.audit_rule_meta.operator</code>.
     */
    public String getOperator() {
        return (String) get(8);
    }

    /**
     * Setter for <code>material.audit_rule_meta.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>material.audit_rule_meta.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>material.audit_rule_meta.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>material.audit_rule_meta.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, Integer, String, String, String, Integer, Integer, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, Integer, String, String, String, Integer, Integer, Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AuditRuleMeta.AUDIT_RULE_META.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AuditRuleMeta.AUDIT_RULE_META.ENTITY_TYPE;
    }

    @Override
    public Field<String> field3() {
        return AuditRuleMeta.AUDIT_RULE_META.FIELD;
    }

    @Override
    public Field<String> field4() {
        return AuditRuleMeta.AUDIT_RULE_META.NAME;
    }

    @Override
    public Field<String> field5() {
        return AuditRuleMeta.AUDIT_RULE_META.FACT_FIELD;
    }

    @Override
    public Field<Integer> field6() {
        return AuditRuleMeta.AUDIT_RULE_META.FACT_MULTIPLE;
    }

    @Override
    public Field<Integer> field7() {
        return AuditRuleMeta.AUDIT_RULE_META.FIELD_TYPE;
    }

    @Override
    public Field<Integer> field8() {
        return AuditRuleMeta.AUDIT_RULE_META.STATE;
    }

    @Override
    public Field<String> field9() {
        return AuditRuleMeta.AUDIT_RULE_META.OPERATOR;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return AuditRuleMeta.AUDIT_RULE_META.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return AuditRuleMeta.AUDIT_RULE_META.MODIFY_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getEntityType();
    }

    @Override
    public String component3() {
        return getField();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getFactField();
    }

    @Override
    public Integer component6() {
        return getFactMultiple();
    }

    @Override
    public Integer component7() {
        return getFieldType();
    }

    @Override
    public Integer component8() {
        return getState();
    }

    @Override
    public String component9() {
        return getOperator();
    }

    @Override
    public LocalDateTime component10() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component11() {
        return getModifyTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getEntityType();
    }

    @Override
    public String value3() {
        return getField();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getFactField();
    }

    @Override
    public Integer value6() {
        return getFactMultiple();
    }

    @Override
    public Integer value7() {
        return getFieldType();
    }

    @Override
    public Integer value8() {
        return getState();
    }

    @Override
    public String value9() {
        return getOperator();
    }

    @Override
    public LocalDateTime value10() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value11() {
        return getModifyTime();
    }

    @Override
    public AuditRuleMetaRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AuditRuleMetaRecord value2(Integer value) {
        setEntityType(value);
        return this;
    }

    @Override
    public AuditRuleMetaRecord value3(String value) {
        setField(value);
        return this;
    }

    @Override
    public AuditRuleMetaRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public AuditRuleMetaRecord value5(String value) {
        setFactField(value);
        return this;
    }

    @Override
    public AuditRuleMetaRecord value6(Integer value) {
        setFactMultiple(value);
        return this;
    }

    @Override
    public AuditRuleMetaRecord value7(Integer value) {
        setFieldType(value);
        return this;
    }

    @Override
    public AuditRuleMetaRecord value8(Integer value) {
        setState(value);
        return this;
    }

    @Override
    public AuditRuleMetaRecord value9(String value) {
        setOperator(value);
        return this;
    }

    @Override
    public AuditRuleMetaRecord value10(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public AuditRuleMetaRecord value11(LocalDateTime value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public AuditRuleMetaRecord values(Long value1, Integer value2, String value3, String value4, String value5, Integer value6, Integer value7, Integer value8, String value9, LocalDateTime value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuditRuleMetaRecord
     */
    public AuditRuleMetaRecord() {
        super(AuditRuleMeta.AUDIT_RULE_META);
    }

    /**
     * Create a detached, initialised AuditRuleMetaRecord
     */
    public AuditRuleMetaRecord(Long id, Integer entityType, String field, String name, String factField, Integer factMultiple, Integer fieldType, Integer state, String operator, LocalDateTime createTime, LocalDateTime modifyTime) {
        super(AuditRuleMeta.AUDIT_RULE_META);

        setId(id);
        setEntityType(entityType);
        setField(field);
        setName(name);
        setFactField(factField);
        setFactMultiple(factMultiple);
        setFieldType(fieldType);
        setState(state);
        setOperator(operator);
        setCreateTime(createTime);
        setModifyTime(modifyTime);
    }

    /**
     * Create a detached, initialised AuditRuleMetaRecord
     */
    public AuditRuleMetaRecord(com.tengzhe.jooq.data.material.tables.pojos.AuditRuleMeta value) {
        super(AuditRuleMeta.AUDIT_RULE_META);

        if (value != null) {
            setId(value.getId());
            setEntityType(value.getEntityType());
            setField(value.getField());
            setName(value.getName());
            setFactField(value.getFactField());
            setFactMultiple(value.getFactMultiple());
            setFieldType(value.getFieldType());
            setState(value.getState());
            setOperator(value.getOperator());
            setCreateTime(value.getCreateTime());
            setModifyTime(value.getModifyTime());
        }
    }
}
