/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.audit_wolong.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountRelation implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private Long          userid;
    private String        userName;
    private Integer       type;
    private Long          targetId;
    private String        targetName;
    private LocalDateTime createTime;
    private LocalDateTime modifyTime;

    public AccountRelation() {}

    public AccountRelation(AccountRelation value) {
        this.id = value.id;
        this.userid = value.userid;
        this.userName = value.userName;
        this.type = value.type;
        this.targetId = value.targetId;
        this.targetName = value.targetName;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
    }

    public AccountRelation(
        Long          id,
        Long          userid,
        String        userName,
        Integer       type,
        Long          targetId,
        String        targetName,
        LocalDateTime createTime,
        LocalDateTime modifyTime
    ) {
        this.id = id;
        this.userid = userid;
        this.userName = userName;
        this.type = type;
        this.targetId = targetId;
        this.targetName = targetName;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }

    /**
     * Getter for <code>audit_wolong.account_relation.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>audit_wolong.account_relation.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>audit_wolong.account_relation.userid</code>.
     */
    public Long getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>audit_wolong.account_relation.userid</code>.
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * Getter for <code>audit_wolong.account_relation.user_name</code>.
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>audit_wolong.account_relation.user_name</code>.
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Getter for <code>audit_wolong.account_relation.type</code>.
     */
    public Integer getType() {
        return this.type;
    }

    /**
     * Setter for <code>audit_wolong.account_relation.type</code>.
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * Getter for <code>audit_wolong.account_relation.target_id</code>.
     */
    public Long getTargetId() {
        return this.targetId;
    }

    /**
     * Setter for <code>audit_wolong.account_relation.target_id</code>.
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * Getter for <code>audit_wolong.account_relation.target_name</code>.
     */
    public String getTargetName() {
        return this.targetName;
    }

    /**
     * Setter for <code>audit_wolong.account_relation.target_name</code>.
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }

    /**
     * Getter for <code>audit_wolong.account_relation.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>audit_wolong.account_relation.create_time</code>.
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>audit_wolong.account_relation.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    /**
     * Setter for <code>audit_wolong.account_relation.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountRelation (");

        sb.append(id);
        sb.append(", ").append(userid);
        sb.append(", ").append(userName);
        sb.append(", ").append(type);
        sb.append(", ").append(targetId);
        sb.append(", ").append(targetName);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);

        sb.append(")");
        return sb.toString();
    }
}
