/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.audit_wolong.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuditSensitiveUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private Long          operatorid;
    private Long          sensitiveUserid;
    private String        addReason;
    private String        remark;
    private LocalDateTime createTime;
    private LocalDateTime modifyTime;

    public AuditSensitiveUser() {}

    public AuditSensitiveUser(AuditSensitiveUser value) {
        this.id = value.id;
        this.operatorid = value.operatorid;
        this.sensitiveUserid = value.sensitiveUserid;
        this.addReason = value.addReason;
        this.remark = value.remark;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
    }

    public AuditSensitiveUser(
        Long          id,
        Long          operatorid,
        Long          sensitiveUserid,
        String        addReason,
        String        remark,
        LocalDateTime createTime,
        LocalDateTime modifyTime
    ) {
        this.id = id;
        this.operatorid = operatorid;
        this.sensitiveUserid = sensitiveUserid;
        this.addReason = addReason;
        this.remark = remark;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }

    /**
     * Getter for <code>audit_wolong.audit_sensitive_user.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>audit_wolong.audit_sensitive_user.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>audit_wolong.audit_sensitive_user.operatorid</code>.
     */
    public Long getOperatorid() {
        return this.operatorid;
    }

    /**
     * Setter for <code>audit_wolong.audit_sensitive_user.operatorid</code>.
     */
    public void setOperatorid(Long operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * Getter for
     * <code>audit_wolong.audit_sensitive_user.sensitive_userid</code>.
     */
    public Long getSensitiveUserid() {
        return this.sensitiveUserid;
    }

    /**
     * Setter for
     * <code>audit_wolong.audit_sensitive_user.sensitive_userid</code>.
     */
    public void setSensitiveUserid(Long sensitiveUserid) {
        this.sensitiveUserid = sensitiveUserid;
    }

    /**
     * Getter for <code>audit_wolong.audit_sensitive_user.add_reason</code>.
     */
    public String getAddReason() {
        return this.addReason;
    }

    /**
     * Setter for <code>audit_wolong.audit_sensitive_user.add_reason</code>.
     */
    public void setAddReason(String addReason) {
        this.addReason = addReason;
    }

    /**
     * Getter for <code>audit_wolong.audit_sensitive_user.remark</code>.
     */
    public String getRemark() {
        return this.remark;
    }

    /**
     * Setter for <code>audit_wolong.audit_sensitive_user.remark</code>.
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * Getter for <code>audit_wolong.audit_sensitive_user.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>audit_wolong.audit_sensitive_user.create_time</code>.
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>audit_wolong.audit_sensitive_user.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    /**
     * Setter for <code>audit_wolong.audit_sensitive_user.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuditSensitiveUser (");

        sb.append(id);
        sb.append(", ").append(operatorid);
        sb.append(", ").append(sensitiveUserid);
        sb.append(", ").append(addReason);
        sb.append(", ").append(remark);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);

        sb.append(")");
        return sb.toString();
    }
}
