/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.audit_wolong.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PictureManualAuditResult implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private Long          pictureId;
    private String        pictureUrl;
    private Integer       state;
    private LocalDateTime createTime;
    private LocalDateTime modifyTime;

    public PictureManualAuditResult() {}

    public PictureManualAuditResult(PictureManualAuditResult value) {
        this.id = value.id;
        this.pictureId = value.pictureId;
        this.pictureUrl = value.pictureUrl;
        this.state = value.state;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
    }

    public PictureManualAuditResult(
        Long          id,
        Long          pictureId,
        String        pictureUrl,
        Integer       state,
        LocalDateTime createTime,
        LocalDateTime modifyTime
    ) {
        this.id = id;
        this.pictureId = pictureId;
        this.pictureUrl = pictureUrl;
        this.state = state;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }

    /**
     * Getter for <code>audit_wolong.picture_manual_audit_result.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>audit_wolong.picture_manual_audit_result.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>audit_wolong.picture_manual_audit_result.picture_id</code>.
     */
    public Long getPictureId() {
        return this.pictureId;
    }

    /**
     * Setter for
     * <code>audit_wolong.picture_manual_audit_result.picture_id</code>.
     */
    public void setPictureId(Long pictureId) {
        this.pictureId = pictureId;
    }

    /**
     * Getter for
     * <code>audit_wolong.picture_manual_audit_result.picture_url</code>.
     */
    public String getPictureUrl() {
        return this.pictureUrl;
    }

    /**
     * Setter for
     * <code>audit_wolong.picture_manual_audit_result.picture_url</code>.
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
    }

    /**
     * Getter for <code>audit_wolong.picture_manual_audit_result.state</code>.
     */
    public Integer getState() {
        return this.state;
    }

    /**
     * Setter for <code>audit_wolong.picture_manual_audit_result.state</code>.
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * Getter for
     * <code>audit_wolong.picture_manual_audit_result.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for
     * <code>audit_wolong.picture_manual_audit_result.create_time</code>.
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for
     * <code>audit_wolong.picture_manual_audit_result.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    /**
     * Setter for
     * <code>audit_wolong.picture_manual_audit_result.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PictureManualAuditResult (");

        sb.append(id);
        sb.append(", ").append(pictureId);
        sb.append(", ").append(pictureUrl);
        sb.append(", ").append(state);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);

        sb.append(")");
        return sb.toString();
    }
}
