/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.material.tables;


import com.tengzhe.jooq.data.material.Keys;
import com.tengzhe.jooq.data.material.Material;
import com.tengzhe.jooq.data.material.tables.records.AuditBrandTargetUrlRecord;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row15;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuditBrandTargetUrl extends TableImpl<AuditBrandTargetUrlRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>material.audit_brand_target_url</code>
     */
    public static final AuditBrandTargetUrl AUDIT_BRAND_TARGET_URL = new AuditBrandTargetUrl();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuditBrandTargetUrlRecord> getRecordType() {
        return AuditBrandTargetUrlRecord.class;
    }

    /**
     * The column <code>material.audit_brand_target_url.id</code>.
     */
    public final TableField<AuditBrandTargetUrlRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>material.audit_brand_target_url.entity_id</code>.
     */
    public final TableField<AuditBrandTargetUrlRecord, Long> ENTITY_ID = createField(DSL.name("entity_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("'-1'", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>material.audit_brand_target_url.version</code>.
     */
    public final TableField<AuditBrandTargetUrlRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("'-1'", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>material.audit_brand_target_url.audit_type</code>.
     */
    public final TableField<AuditBrandTargetUrlRecord, Integer> AUDIT_TYPE = createField(DSL.name("audit_type"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("'-1'", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>material.audit_brand_target_url.user_id</code>.
     */
    public final TableField<AuditBrandTargetUrlRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("'-1'", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>material.audit_brand_target_url.audit_state</code>.
     */
    public final TableField<AuditBrandTargetUrlRecord, Integer> AUDIT_STATE = createField(DSL.name("audit_state"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("'-1'", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>material.audit_brand_target_url.auditor_id</code>.
     */
    public final TableField<AuditBrandTargetUrlRecord, Long> AUDITOR_ID = createField(DSL.name("auditor_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("'-1'", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>material.audit_brand_target_url.reason_code</code>.
     */
    public final TableField<AuditBrandTargetUrlRecord, String> REASON_CODE = createField(DSL.name("reason_code"), SQLDataType.VARCHAR(4096).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>material.audit_brand_target_url.reason</code>.
     */
    public final TableField<AuditBrandTargetUrlRecord, String> REASON = createField(DSL.name("reason"), SQLDataType.VARCHAR(4096).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>material.audit_brand_target_url.audit_start_time</code>.
     */
    public final TableField<AuditBrandTargetUrlRecord, LocalDateTime> AUDIT_START_TIME = createField(DSL.name("audit_start_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>material.audit_brand_target_url.audit_end_time</code>.
     */
    public final TableField<AuditBrandTargetUrlRecord, LocalDateTime> AUDIT_END_TIME = createField(DSL.name("audit_end_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("'2000-01-01 00:00:00'", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>material.audit_brand_target_url.extend</code>.
     */
    public final TableField<AuditBrandTargetUrlRecord, String> EXTEND = createField(DSL.name("extend"), SQLDataType.VARCHAR(4096).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>material.audit_brand_target_url.modify_time</code>.
     */
    public final TableField<AuditBrandTargetUrlRecord, LocalDateTime> MODIFY_TIME = createField(DSL.name("modify_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>material.audit_brand_target_url.modify_day_tag</code>.
     */
    public final TableField<AuditBrandTargetUrlRecord, Integer> MODIFY_DAY_TAG = createField(DSL.name("modify_day_tag"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("'-1'", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>material.audit_brand_target_url.create_time</code>.
     */
    public final TableField<AuditBrandTargetUrlRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private AuditBrandTargetUrl(Name alias, Table<AuditBrandTargetUrlRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuditBrandTargetUrl(Name alias, Table<AuditBrandTargetUrlRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>material.audit_brand_target_url</code> table
     * reference
     */
    public AuditBrandTargetUrl(String alias) {
        this(DSL.name(alias), AUDIT_BRAND_TARGET_URL);
    }

    /**
     * Create an aliased <code>material.audit_brand_target_url</code> table
     * reference
     */
    public AuditBrandTargetUrl(Name alias) {
        this(alias, AUDIT_BRAND_TARGET_URL);
    }

    /**
     * Create a <code>material.audit_brand_target_url</code> table reference
     */
    public AuditBrandTargetUrl() {
        this(DSL.name("audit_brand_target_url"), null);
    }

    public <O extends Record> AuditBrandTargetUrl(Table<O> child, ForeignKey<O, AuditBrandTargetUrlRecord> key) {
        super(child, key, AUDIT_BRAND_TARGET_URL);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Material.MATERIAL;
    }

    @Override
    public Identity<AuditBrandTargetUrlRecord, Long> getIdentity() {
        return (Identity<AuditBrandTargetUrlRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AuditBrandTargetUrlRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_5F;
    }

    @Override
    public AuditBrandTargetUrl as(String alias) {
        return new AuditBrandTargetUrl(DSL.name(alias), this);
    }

    @Override
    public AuditBrandTargetUrl as(Name alias) {
        return new AuditBrandTargetUrl(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditBrandTargetUrl rename(String name) {
        return new AuditBrandTargetUrl(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditBrandTargetUrl rename(Name name) {
        return new AuditBrandTargetUrl(name, null);
    }

    // -------------------------------------------------------------------------
    // Row15 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row15<Long, Long, Long, Integer, Long, Integer, Long, String, String, LocalDateTime, LocalDateTime, String, LocalDateTime, Integer, LocalDateTime> fieldsRow() {
        return (Row15) super.fieldsRow();
    }
}
