/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.material.tables;


import com.tengzhe.jooq.data.material.Keys;
import com.tengzhe.jooq.data.material.Material;
import com.tengzhe.jooq.data.material.tables.records.AuditAttachCreativeLogHistoryRecord;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row17;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuditAttachCreativeLogHistory extends TableImpl<AuditAttachCreativeLogHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>material.audit_attach_creative_log_history</code>
     */
    public static final AuditAttachCreativeLogHistory AUDIT_ATTACH_CREATIVE_LOG_HISTORY = new AuditAttachCreativeLogHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuditAttachCreativeLogHistoryRecord> getRecordType() {
        return AuditAttachCreativeLogHistoryRecord.class;
    }

    /**
     * The column <code>material.audit_attach_creative_log_history.id</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>material.audit_attach_creative_log_history.attach_creative_id</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, Long> ATTACH_CREATIVE_ID = createField(DSL.name("attach_creative_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>material.audit_attach_creative_log_history.uc_id</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, Long> UC_ID = createField(DSL.name("uc_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>material.audit_attach_creative_log_history.user_id</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>material.audit_attach_creative_log_history.group_id</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, Long> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>material.audit_attach_creative_log_history.campaign_id</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, Long> CAMPAIGN_ID = createField(DSL.name("campaign_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>material.audit_attach_creative_log_history.description</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>material.audit_attach_creative_log_history.extra_style_id</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, Integer> EXTRA_STYLE_ID = createField(DSL.name("extra_style_id"), SQLDataType.INTEGER.defaultValue(DSL.field("'-1'", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>material.audit_attach_creative_log_history.component_id</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, Long> COMPONENT_ID = createField(DSL.name("component_id"), SQLDataType.BIGINT.defaultValue(DSL.field("'0'", SQLDataType.BIGINT)), this, "");

    /**
     * The column
     * <code>material.audit_attach_creative_log_history.content</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>material.audit_attach_creative_log_history.logic_state</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, Integer> LOGIC_STATE = createField(DSL.name("logic_state"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>material.audit_attach_creative_log_history.version</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.defaultValue(DSL.field("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>material.audit_attach_creative_log_history.state</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, Integer> STATE = createField(DSL.name("state"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("'1'", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>material.audit_attach_creative_log_history.state_detail</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, Integer> STATE_DETAIL = createField(DSL.name("state_detail"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("'-1'", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>material.audit_attach_creative_log_history.audit_type</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, String> AUDIT_TYPE = createField(DSL.name("audit_type"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>material.audit_attach_creative_log_history.audit_detail</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, String> AUDIT_DETAIL = createField(DSL.name("audit_detail"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>material.audit_attach_creative_log_history.create_time</code>.
     */
    public final TableField<AuditAttachCreativeLogHistoryRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private AuditAttachCreativeLogHistory(Name alias, Table<AuditAttachCreativeLogHistoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuditAttachCreativeLogHistory(Name alias, Table<AuditAttachCreativeLogHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>material.audit_attach_creative_log_history</code>
     * table reference
     */
    public AuditAttachCreativeLogHistory(String alias) {
        this(DSL.name(alias), AUDIT_ATTACH_CREATIVE_LOG_HISTORY);
    }

    /**
     * Create an aliased <code>material.audit_attach_creative_log_history</code>
     * table reference
     */
    public AuditAttachCreativeLogHistory(Name alias) {
        this(alias, AUDIT_ATTACH_CREATIVE_LOG_HISTORY);
    }

    /**
     * Create a <code>material.audit_attach_creative_log_history</code> table
     * reference
     */
    public AuditAttachCreativeLogHistory() {
        this(DSL.name("audit_attach_creative_log_history"), null);
    }

    public <O extends Record> AuditAttachCreativeLogHistory(Table<O> child, ForeignKey<O, AuditAttachCreativeLogHistoryRecord> key) {
        super(child, key, AUDIT_ATTACH_CREATIVE_LOG_HISTORY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Material.MATERIAL;
    }

    @Override
    public Identity<AuditAttachCreativeLogHistoryRecord, Long> getIdentity() {
        return (Identity<AuditAttachCreativeLogHistoryRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AuditAttachCreativeLogHistoryRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_FA;
    }

    @Override
    public AuditAttachCreativeLogHistory as(String alias) {
        return new AuditAttachCreativeLogHistory(DSL.name(alias), this);
    }

    @Override
    public AuditAttachCreativeLogHistory as(Name alias) {
        return new AuditAttachCreativeLogHistory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditAttachCreativeLogHistory rename(String name) {
        return new AuditAttachCreativeLogHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditAttachCreativeLogHistory rename(Name name) {
        return new AuditAttachCreativeLogHistory(name, null);
    }

    // -------------------------------------------------------------------------
    // Row17 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row17<Long, Long, Long, Long, Long, Long, String, Integer, Long, String, Integer, Long, Integer, Integer, String, String, LocalDateTime> fieldsRow() {
        return (Row17) super.fieldsRow();
    }
}
