/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.material.tables;


import com.tengzhe.jooq.data.material.Keys;
import com.tengzhe.jooq.data.material.Material;
import com.tengzhe.jooq.data.material.tables.records.CptQmxingPackageDetailRecord;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CptQmxingPackageDetail extends TableImpl<CptQmxingPackageDetailRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>material.cpt_qmxing_package_detail</code>
     */
    public static final CptQmxingPackageDetail CPT_QMXING_PACKAGE_DETAIL = new CptQmxingPackageDetail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CptQmxingPackageDetailRecord> getRecordType() {
        return CptQmxingPackageDetailRecord.class;
    }

    /**
     * The column <code>material.cpt_qmxing_package_detail.id</code>.
     */
    public final TableField<CptQmxingPackageDetailRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>material.cpt_qmxing_package_detail.package_id</code>.
     */
    public final TableField<CptQmxingPackageDetailRecord, Long> PACKAGE_ID = createField(DSL.name("package_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>material.cpt_qmxing_package_detail.audit_state</code>.
     */
    public final TableField<CptQmxingPackageDetailRecord, Integer> AUDIT_STATE = createField(DSL.name("audit_state"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("'1'", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package_detail.word</code>.
     */
    public final TableField<CptQmxingPackageDetailRecord, String> WORD = createField(DSL.name("word"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package_detail.auditor_id</code>.
     */
    public final TableField<CptQmxingPackageDetailRecord, Long> AUDITOR_ID = createField(DSL.name("auditor_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("'-1'", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package_detail.reason_code</code>.
     */
    public final TableField<CptQmxingPackageDetailRecord, String> REASON_CODE = createField(DSL.name("reason_code"), SQLDataType.VARCHAR(4096).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package_detail.reason</code>.
     */
    public final TableField<CptQmxingPackageDetailRecord, String> REASON = createField(DSL.name("reason"), SQLDataType.VARCHAR(4096).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package_detail.create_time</code>.
     */
    public final TableField<CptQmxingPackageDetailRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package_detail.modify_time</code>.
     */
    public final TableField<CptQmxingPackageDetailRecord, LocalDateTime> MODIFY_TIME = createField(DSL.name("modify_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private CptQmxingPackageDetail(Name alias, Table<CptQmxingPackageDetailRecord> aliased) {
        this(alias, aliased, null);
    }

    private CptQmxingPackageDetail(Name alias, Table<CptQmxingPackageDetailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>material.cpt_qmxing_package_detail</code> table
     * reference
     */
    public CptQmxingPackageDetail(String alias) {
        this(DSL.name(alias), CPT_QMXING_PACKAGE_DETAIL);
    }

    /**
     * Create an aliased <code>material.cpt_qmxing_package_detail</code> table
     * reference
     */
    public CptQmxingPackageDetail(Name alias) {
        this(alias, CPT_QMXING_PACKAGE_DETAIL);
    }

    /**
     * Create a <code>material.cpt_qmxing_package_detail</code> table reference
     */
    public CptQmxingPackageDetail() {
        this(DSL.name("cpt_qmxing_package_detail"), null);
    }

    public <O extends Record> CptQmxingPackageDetail(Table<O> child, ForeignKey<O, CptQmxingPackageDetailRecord> key) {
        super(child, key, CPT_QMXING_PACKAGE_DETAIL);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Material.MATERIAL;
    }

    @Override
    public Identity<CptQmxingPackageDetailRecord, Long> getIdentity() {
        return (Identity<CptQmxingPackageDetailRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CptQmxingPackageDetailRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_CEB;
    }

    @Override
    public CptQmxingPackageDetail as(String alias) {
        return new CptQmxingPackageDetail(DSL.name(alias), this);
    }

    @Override
    public CptQmxingPackageDetail as(Name alias) {
        return new CptQmxingPackageDetail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CptQmxingPackageDetail rename(String name) {
        return new CptQmxingPackageDetail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CptQmxingPackageDetail rename(Name name) {
        return new CptQmxingPackageDetail(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, Integer, String, Long, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
