/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.material.tables;


import com.tengzhe.jooq.data.material.Keys;
import com.tengzhe.jooq.data.material.Material;
import com.tengzhe.jooq.data.material.tables.records.CptQmxingPackageRecord;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row19;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CptQmxingPackage extends TableImpl<CptQmxingPackageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>material.cpt_qmxing_package</code>
     */
    public static final CptQmxingPackage CPT_QMXING_PACKAGE = new CptQmxingPackage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CptQmxingPackageRecord> getRecordType() {
        return CptQmxingPackageRecord.class;
    }

    /**
     * The column <code>material.cpt_qmxing_package.id</code>.
     */
    public final TableField<CptQmxingPackageRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.uc_id</code>.
     */
    public final TableField<CptQmxingPackageRecord, Long> UC_ID = createField(DSL.name("uc_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.user_id</code>.
     */
    public final TableField<CptQmxingPackageRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.package_name</code>.
     */
    public final TableField<CptQmxingPackageRecord, String> PACKAGE_NAME = createField(DSL.name("package_name"), SQLDataType.VARCHAR(300).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.company_name</code>.
     */
    public final TableField<CptQmxingPackageRecord, String> COMPANY_NAME = createField(DSL.name("company_name"), SQLDataType.VARCHAR(300).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.brand_name</code>.
     */
    public final TableField<CptQmxingPackageRecord, String> BRAND_NAME = createField(DSL.name("brand_name"), SQLDataType.VARCHAR(300).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.launch_region</code>.
     */
    public final TableField<CptQmxingPackageRecord, String> LAUNCH_REGION = createField(DSL.name("launch_region"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.attachments</code>.
     */
    public final TableField<CptQmxingPackageRecord, String> ATTACHMENTS = createField(DSL.name("attachments"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.site_url</code>.
     */
    public final TableField<CptQmxingPackageRecord, String> SITE_URL = createField(DSL.name("site_url"), SQLDataType.VARCHAR(1024).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.audit_word_file</code>.
     */
    public final TableField<CptQmxingPackageRecord, String> AUDIT_WORD_FILE = createField(DSL.name("audit_word_file"), SQLDataType.VARCHAR(1024).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.pass_word_file</code>.
     */
    public final TableField<CptQmxingPackageRecord, String> PASS_WORD_FILE = createField(DSL.name("pass_word_file"), SQLDataType.VARCHAR(1024).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.reject_word_file</code>.
     */
    public final TableField<CptQmxingPackageRecord, String> REJECT_WORD_FILE = createField(DSL.name("reject_word_file"), SQLDataType.VARCHAR(1024).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.version</code>.
     */
    public final TableField<CptQmxingPackageRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.create_user_id</code>.
     */
    public final TableField<CptQmxingPackageRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.logic_state</code>.
     */
    public final TableField<CptQmxingPackageRecord, Integer> LOGIC_STATE = createField(DSL.name("logic_state"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.state</code>.
     */
    public final TableField<CptQmxingPackageRecord, Integer> STATE = createField(DSL.name("state"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("'1'", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.state_detail</code>.
     */
    public final TableField<CptQmxingPackageRecord, Integer> STATE_DETAIL = createField(DSL.name("state_detail"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("'-1'", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.create_time</code>.
     */
    public final TableField<CptQmxingPackageRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>material.cpt_qmxing_package.modify_time</code>.
     */
    public final TableField<CptQmxingPackageRecord, LocalDateTime> MODIFY_TIME = createField(DSL.name("modify_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private CptQmxingPackage(Name alias, Table<CptQmxingPackageRecord> aliased) {
        this(alias, aliased, null);
    }

    private CptQmxingPackage(Name alias, Table<CptQmxingPackageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>material.cpt_qmxing_package</code> table
     * reference
     */
    public CptQmxingPackage(String alias) {
        this(DSL.name(alias), CPT_QMXING_PACKAGE);
    }

    /**
     * Create an aliased <code>material.cpt_qmxing_package</code> table
     * reference
     */
    public CptQmxingPackage(Name alias) {
        this(alias, CPT_QMXING_PACKAGE);
    }

    /**
     * Create a <code>material.cpt_qmxing_package</code> table reference
     */
    public CptQmxingPackage() {
        this(DSL.name("cpt_qmxing_package"), null);
    }

    public <O extends Record> CptQmxingPackage(Table<O> child, ForeignKey<O, CptQmxingPackageRecord> key) {
        super(child, key, CPT_QMXING_PACKAGE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Material.MATERIAL;
    }

    @Override
    public UniqueKey<CptQmxingPackageRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_C68;
    }

    @Override
    public CptQmxingPackage as(String alias) {
        return new CptQmxingPackage(DSL.name(alias), this);
    }

    @Override
    public CptQmxingPackage as(Name alias) {
        return new CptQmxingPackage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CptQmxingPackage rename(String name) {
        return new CptQmxingPackage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CptQmxingPackage rename(Name name) {
        return new CptQmxingPackage(name, null);
    }

    // -------------------------------------------------------------------------
    // Row19 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row19<Long, Long, Long, String, String, String, String, String, String, String, String, String, Long, Long, Integer, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row19) super.fieldsRow();
    }
}
