/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.naudit.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QualificationRelation implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private Integer       source;
    private Long          qualId;
    private Long          targetId;
    private Integer       targetType;
    private Long          auditorId;
    private Integer       auditState;
    private String        auditResult;
    private LocalDateTime auditTime;
    private LocalDateTime createTime;

    public QualificationRelation() {}

    public QualificationRelation(QualificationRelation value) {
        this.id = value.id;
        this.source = value.source;
        this.qualId = value.qualId;
        this.targetId = value.targetId;
        this.targetType = value.targetType;
        this.auditorId = value.auditorId;
        this.auditState = value.auditState;
        this.auditResult = value.auditResult;
        this.auditTime = value.auditTime;
        this.createTime = value.createTime;
    }

    public QualificationRelation(
        Long          id,
        Integer       source,
        Long          qualId,
        Long          targetId,
        Integer       targetType,
        Long          auditorId,
        Integer       auditState,
        String        auditResult,
        LocalDateTime auditTime,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.source = source;
        this.qualId = qualId;
        this.targetId = targetId;
        this.targetType = targetType;
        this.auditorId = auditorId;
        this.auditState = auditState;
        this.auditResult = auditResult;
        this.auditTime = auditTime;
        this.createTime = createTime;
    }

    /**
     * Getter for <code>naudit.qualification_relation.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>naudit.qualification_relation.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>naudit.qualification_relation.source</code>.
     */
    public Integer getSource() {
        return this.source;
    }

    /**
     * Setter for <code>naudit.qualification_relation.source</code>.
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * Getter for <code>naudit.qualification_relation.qual_id</code>.
     */
    public Long getQualId() {
        return this.qualId;
    }

    /**
     * Setter for <code>naudit.qualification_relation.qual_id</code>.
     */
    public void setQualId(Long qualId) {
        this.qualId = qualId;
    }

    /**
     * Getter for <code>naudit.qualification_relation.target_id</code>.
     */
    public Long getTargetId() {
        return this.targetId;
    }

    /**
     * Setter for <code>naudit.qualification_relation.target_id</code>.
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * Getter for <code>naudit.qualification_relation.target_type</code>.
     */
    public Integer getTargetType() {
        return this.targetType;
    }

    /**
     * Setter for <code>naudit.qualification_relation.target_type</code>.
     */
    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    /**
     * Getter for <code>naudit.qualification_relation.auditor_id</code>.
     */
    public Long getAuditorId() {
        return this.auditorId;
    }

    /**
     * Setter for <code>naudit.qualification_relation.auditor_id</code>.
     */
    public void setAuditorId(Long auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * Getter for <code>naudit.qualification_relation.audit_state</code>.
     */
    public Integer getAuditState() {
        return this.auditState;
    }

    /**
     * Setter for <code>naudit.qualification_relation.audit_state</code>.
     */
    public void setAuditState(Integer auditState) {
        this.auditState = auditState;
    }

    /**
     * Getter for <code>naudit.qualification_relation.audit_result</code>.
     */
    public String getAuditResult() {
        return this.auditResult;
    }

    /**
     * Setter for <code>naudit.qualification_relation.audit_result</code>.
     */
    public void setAuditResult(String auditResult) {
        this.auditResult = auditResult;
    }

    /**
     * Getter for <code>naudit.qualification_relation.audit_time</code>.
     */
    public LocalDateTime getAuditTime() {
        return this.auditTime;
    }

    /**
     * Setter for <code>naudit.qualification_relation.audit_time</code>.
     */
    public void setAuditTime(LocalDateTime auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * Getter for <code>naudit.qualification_relation.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>naudit.qualification_relation.create_time</code>.
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QualificationRelation (");

        sb.append(id);
        sb.append(", ").append(source);
        sb.append(", ").append(qualId);
        sb.append(", ").append(targetId);
        sb.append(", ").append(targetType);
        sb.append(", ").append(auditorId);
        sb.append(", ").append(auditState);
        sb.append(", ").append(auditResult);
        sb.append(", ").append(auditTime);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
