/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.naudit.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UcAccount implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          userId;
    private Long          ucId;
    private Integer       bizType;
    private String        userName;
    private String        companyName;
    private String        siteName;
    private String        siteUrl;
    private Integer       siteTag;
    private Integer       industry1;
    private Integer       industry2;
    private Integer       industry3;
    private String        contact;
    private Integer       source;
    private Integer       adResource;
    private Integer       viewState;
    private Integer       financeState;
    private Integer       logicState;
    private Integer       auditState;
    private Long          auditorId;
    private String        auditResult;
    private LocalDateTime auditTime;
    private LocalDateTime createTime;
    private LocalDateTime modifyTime;
    private Integer       _Flag;

    public UcAccount() {}

    public UcAccount(UcAccount value) {
        this.userId = value.userId;
        this.ucId = value.ucId;
        this.bizType = value.bizType;
        this.userName = value.userName;
        this.companyName = value.companyName;
        this.siteName = value.siteName;
        this.siteUrl = value.siteUrl;
        this.siteTag = value.siteTag;
        this.industry1 = value.industry1;
        this.industry2 = value.industry2;
        this.industry3 = value.industry3;
        this.contact = value.contact;
        this.source = value.source;
        this.adResource = value.adResource;
        this.viewState = value.viewState;
        this.financeState = value.financeState;
        this.logicState = value.logicState;
        this.auditState = value.auditState;
        this.auditorId = value.auditorId;
        this.auditResult = value.auditResult;
        this.auditTime = value.auditTime;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
        this._Flag = value._Flag;
    }

    public UcAccount(
        Long          userId,
        Long          ucId,
        Integer       bizType,
        String        userName,
        String        companyName,
        String        siteName,
        String        siteUrl,
        Integer       siteTag,
        Integer       industry1,
        Integer       industry2,
        Integer       industry3,
        String        contact,
        Integer       source,
        Integer       adResource,
        Integer       viewState,
        Integer       financeState,
        Integer       logicState,
        Integer       auditState,
        Long          auditorId,
        String        auditResult,
        LocalDateTime auditTime,
        LocalDateTime createTime,
        LocalDateTime modifyTime,
        Integer       _Flag
    ) {
        this.userId = userId;
        this.ucId = ucId;
        this.bizType = bizType;
        this.userName = userName;
        this.companyName = companyName;
        this.siteName = siteName;
        this.siteUrl = siteUrl;
        this.siteTag = siteTag;
        this.industry1 = industry1;
        this.industry2 = industry2;
        this.industry3 = industry3;
        this.contact = contact;
        this.source = source;
        this.adResource = adResource;
        this.viewState = viewState;
        this.financeState = financeState;
        this.logicState = logicState;
        this.auditState = auditState;
        this.auditorId = auditorId;
        this.auditResult = auditResult;
        this.auditTime = auditTime;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this._Flag = _Flag;
    }

    /**
     * Getter for <code>naudit.uc_account.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>naudit.uc_account.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>naudit.uc_account.uc_id</code>.
     */
    public Long getUcId() {
        return this.ucId;
    }

    /**
     * Setter for <code>naudit.uc_account.uc_id</code>.
     */
    public void setUcId(Long ucId) {
        this.ucId = ucId;
    }

    /**
     * Getter for <code>naudit.uc_account.biz_type</code>.
     */
    public Integer getBizType() {
        return this.bizType;
    }

    /**
     * Setter for <code>naudit.uc_account.biz_type</code>.
     */
    public void setBizType(Integer bizType) {
        this.bizType = bizType;
    }

    /**
     * Getter for <code>naudit.uc_account.user_name</code>.
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>naudit.uc_account.user_name</code>.
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Getter for <code>naudit.uc_account.company_name</code>.
     */
    public String getCompanyName() {
        return this.companyName;
    }

    /**
     * Setter for <code>naudit.uc_account.company_name</code>.
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * Getter for <code>naudit.uc_account.site_name</code>.
     */
    public String getSiteName() {
        return this.siteName;
    }

    /**
     * Setter for <code>naudit.uc_account.site_name</code>.
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }

    /**
     * Getter for <code>naudit.uc_account.site_url</code>.
     */
    public String getSiteUrl() {
        return this.siteUrl;
    }

    /**
     * Setter for <code>naudit.uc_account.site_url</code>.
     */
    public void setSiteUrl(String siteUrl) {
        this.siteUrl = siteUrl;
    }

    /**
     * Getter for <code>naudit.uc_account.site_tag</code>.
     */
    public Integer getSiteTag() {
        return this.siteTag;
    }

    /**
     * Setter for <code>naudit.uc_account.site_tag</code>.
     */
    public void setSiteTag(Integer siteTag) {
        this.siteTag = siteTag;
    }

    /**
     * Getter for <code>naudit.uc_account.industry1</code>.
     */
    public Integer getIndustry1() {
        return this.industry1;
    }

    /**
     * Setter for <code>naudit.uc_account.industry1</code>.
     */
    public void setIndustry1(Integer industry1) {
        this.industry1 = industry1;
    }

    /**
     * Getter for <code>naudit.uc_account.industry2</code>.
     */
    public Integer getIndustry2() {
        return this.industry2;
    }

    /**
     * Setter for <code>naudit.uc_account.industry2</code>.
     */
    public void setIndustry2(Integer industry2) {
        this.industry2 = industry2;
    }

    /**
     * Getter for <code>naudit.uc_account.industry3</code>.
     */
    public Integer getIndustry3() {
        return this.industry3;
    }

    /**
     * Setter for <code>naudit.uc_account.industry3</code>.
     */
    public void setIndustry3(Integer industry3) {
        this.industry3 = industry3;
    }

    /**
     * Getter for <code>naudit.uc_account.contact</code>.
     */
    public String getContact() {
        return this.contact;
    }

    /**
     * Setter for <code>naudit.uc_account.contact</code>.
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * Getter for <code>naudit.uc_account.source</code>.
     */
    public Integer getSource() {
        return this.source;
    }

    /**
     * Setter for <code>naudit.uc_account.source</code>.
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * Getter for <code>naudit.uc_account.ad_resource</code>.
     */
    public Integer getAdResource() {
        return this.adResource;
    }

    /**
     * Setter for <code>naudit.uc_account.ad_resource</code>.
     */
    public void setAdResource(Integer adResource) {
        this.adResource = adResource;
    }

    /**
     * Getter for <code>naudit.uc_account.view_state</code>.
     */
    public Integer getViewState() {
        return this.viewState;
    }

    /**
     * Setter for <code>naudit.uc_account.view_state</code>.
     */
    public void setViewState(Integer viewState) {
        this.viewState = viewState;
    }

    /**
     * Getter for <code>naudit.uc_account.finance_state</code>.
     */
    public Integer getFinanceState() {
        return this.financeState;
    }

    /**
     * Setter for <code>naudit.uc_account.finance_state</code>.
     */
    public void setFinanceState(Integer financeState) {
        this.financeState = financeState;
    }

    /**
     * Getter for <code>naudit.uc_account.logic_state</code>.
     */
    public Integer getLogicState() {
        return this.logicState;
    }

    /**
     * Setter for <code>naudit.uc_account.logic_state</code>.
     */
    public void setLogicState(Integer logicState) {
        this.logicState = logicState;
    }

    /**
     * Getter for <code>naudit.uc_account.audit_state</code>.
     */
    public Integer getAuditState() {
        return this.auditState;
    }

    /**
     * Setter for <code>naudit.uc_account.audit_state</code>.
     */
    public void setAuditState(Integer auditState) {
        this.auditState = auditState;
    }

    /**
     * Getter for <code>naudit.uc_account.auditor_id</code>.
     */
    public Long getAuditorId() {
        return this.auditorId;
    }

    /**
     * Setter for <code>naudit.uc_account.auditor_id</code>.
     */
    public void setAuditorId(Long auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * Getter for <code>naudit.uc_account.audit_result</code>.
     */
    public String getAuditResult() {
        return this.auditResult;
    }

    /**
     * Setter for <code>naudit.uc_account.audit_result</code>.
     */
    public void setAuditResult(String auditResult) {
        this.auditResult = auditResult;
    }

    /**
     * Getter for <code>naudit.uc_account.audit_time</code>.
     */
    public LocalDateTime getAuditTime() {
        return this.auditTime;
    }

    /**
     * Setter for <code>naudit.uc_account.audit_time</code>.
     */
    public void setAuditTime(LocalDateTime auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * Getter for <code>naudit.uc_account.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>naudit.uc_account.create_time</code>.
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>naudit.uc_account.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    /**
     * Setter for <code>naudit.uc_account.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * Getter for <code>naudit.uc_account._flag</code>.
     */
    public Integer get_Flag() {
        return this._Flag;
    }

    /**
     * Setter for <code>naudit.uc_account._flag</code>.
     */
    public void set_Flag(Integer _Flag) {
        this._Flag = _Flag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UcAccount (");

        sb.append(userId);
        sb.append(", ").append(ucId);
        sb.append(", ").append(bizType);
        sb.append(", ").append(userName);
        sb.append(", ").append(companyName);
        sb.append(", ").append(siteName);
        sb.append(", ").append(siteUrl);
        sb.append(", ").append(siteTag);
        sb.append(", ").append(industry1);
        sb.append(", ").append(industry2);
        sb.append(", ").append(industry3);
        sb.append(", ").append(contact);
        sb.append(", ").append(source);
        sb.append(", ").append(adResource);
        sb.append(", ").append(viewState);
        sb.append(", ").append(financeState);
        sb.append(", ").append(logicState);
        sb.append(", ").append(auditState);
        sb.append(", ").append(auditorId);
        sb.append(", ").append(auditResult);
        sb.append(", ").append(auditTime);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);
        sb.append(", ").append(_Flag);

        sb.append(")");
        return sb.toString();
    }
}
