spring:
  sql:
    init:
      platform: h2
      mode: embedded #never
  jooq:
    sql-dialect: h2
  datasource:
    url: "jdbc:h2:mem:test"
    username: sa
    password: sa
    hikari:
      jdbc-url: "jdbc:h2:mem:test"
      driver-class-name: org.h2.Driver
      minimum-idle: 5
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: HikariDataSource4H2
      auto-commit: true
      idle-timeout: 30000
      maximum-pool-size: 15
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF8
        zeroDateTimeBehavior: round
        autoReconnect: true
        audit_dict:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
#        web-admin-password:
