/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.audit;


import com.tengzhe.jooq.data.DefaultCatalog;
import com.tengzhe.jooq.data.audit.tables.AuditHuichuanDownloadUrlDetail;
import com.tengzhe.jooq.data.audit.tables.HuichuanIdeaKeyFrame;
import com.tengzhe.jooq.data.audit.tables.UserInfo;
import com.tengzhe.jooq.data.audit.tables.UserInfoConfig;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Audit extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>audit</code>
     */
    public static final Audit AUDIT = new Audit();

    /**
     * The table <code>audit.audit_huichuan_download_url_detail</code>.
     */
    public final AuditHuichuanDownloadUrlDetail AUDIT_HUICHUAN_DOWNLOAD_URL_DETAIL = AuditHuichuanDownloadUrlDetail.AUDIT_HUICHUAN_DOWNLOAD_URL_DETAIL;

    /**
     * The table <code>audit.huichuan_idea_key_frame</code>.
     */
    public final HuichuanIdeaKeyFrame HUICHUAN_IDEA_KEY_FRAME = HuichuanIdeaKeyFrame.HUICHUAN_IDEA_KEY_FRAME;

    /**
     * The table <code>audit.user_info</code>.
     */
    public final UserInfo USER_INFO = UserInfo.USER_INFO;

    /**
     * The table <code>audit.user_info_config</code>.
     */
    public final UserInfoConfig USER_INFO_CONFIG = UserInfoConfig.USER_INFO_CONFIG;

    /**
     * No further instances allowed
     */
    private Audit() {
        super("audit", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuditHuichuanDownloadUrlDetail.AUDIT_HUICHUAN_DOWNLOAD_URL_DETAIL,
            HuichuanIdeaKeyFrame.HUICHUAN_IDEA_KEY_FRAME,
            UserInfo.USER_INFO,
            UserInfoConfig.USER_INFO_CONFIG
        );
    }
}
