spring:
  sql:
    init:
      platform: h2
      mode: embedded #never
  jooq:
    sql-dialect: MYSQL
  datasource:
#    url: "jdbc:log4jdbc:h2:mem:test"
    url: "jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC"
    username: root
    password: root
#    driver-class-name: net.sf.log4jdbc.DriverSpy