spring:
  sql:
    init:
      platform: h2
      mode: embedded #never
  jooq:
    sql-dialect: MYSQL
  datasource:
#    url: "jdbc:log4jdbc:h2:mem:test"
    url: "jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC"
    username: root
    password: root
  shardingsphere:
    rules:
      sharding:
        default-table-strategy:
          standard:
            shardingColumn: tenant_code
            sharding-algorithm-name: database_inline
      tables:
        account:
          actual-data-nodes: ds0.account