/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.audit.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HuichuanIdeaKeyFrame implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long       id;
    private BigDecimal userId;
    private Long       ideaId;
    private String     videoUrl;
    private String     content;

    public HuichuanIdeaKeyFrame() {}

    public HuichuanIdeaKeyFrame(HuichuanIdeaKeyFrame value) {
        this.id = value.id;
        this.userId = value.userId;
        this.ideaId = value.ideaId;
        this.videoUrl = value.videoUrl;
        this.content = value.content;
    }

    public HuichuanIdeaKeyFrame(
        Long       id,
        BigDecimal userId,
        Long       ideaId,
        String     videoUrl,
        String     content
    ) {
        this.id = id;
        this.userId = userId;
        this.ideaId = ideaId;
        this.videoUrl = videoUrl;
        this.content = content;
    }

    /**
     * Getter for <code>audit.huichuan_idea_key_frame.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>audit.huichuan_idea_key_frame.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>audit.huichuan_idea_key_frame.user_id</code>.
     */
    public BigDecimal getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>audit.huichuan_idea_key_frame.user_id</code>.
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>audit.huichuan_idea_key_frame.idea_id</code>.
     */
    public Long getIdeaId() {
        return this.ideaId;
    }

    /**
     * Setter for <code>audit.huichuan_idea_key_frame.idea_id</code>.
     */
    public void setIdeaId(Long ideaId) {
        this.ideaId = ideaId;
    }

    /**
     * Getter for <code>audit.huichuan_idea_key_frame.video_url</code>.
     */
    public String getVideoUrl() {
        return this.videoUrl;
    }

    /**
     * Setter for <code>audit.huichuan_idea_key_frame.video_url</code>.
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    /**
     * Getter for <code>audit.huichuan_idea_key_frame.content</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>audit.huichuan_idea_key_frame.content</code>.
     */
    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HuichuanIdeaKeyFrame (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(ideaId);
        sb.append(", ").append(videoUrl);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
