/*
 * This file is generated by jOOQ.
 */
package com.katana.jooq.entity.audit;


import com.katana.jooq.entity.audit.tables.UserInfo;
import com.katana.jooq.entity.audit.tables.UserInfoConfig;
import com.katana.jooq.entity.audit.tables.records.UserInfoConfigRecord;
import com.katana.jooq.entity.audit.tables.records.UserInfoRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * audit.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserInfoRecord> CONSTRAINT_1 = Internal.createUniqueKey(UserInfo.USER_INFO, DSL.name("CONSTRAINT_1"), new TableField[] { UserInfo.USER_INFO.USERID }, true);
    public static final UniqueKey<UserInfoConfigRecord> CONSTRAINT_1A = Internal.createUniqueKey(UserInfoConfig.USER_INFO_CONFIG, DSL.name("CONSTRAINT_1A"), new TableField[] { UserInfoConfig.USER_INFO_CONFIG.ID }, true);
}
