spring:
  application:
    name: katana-jooq
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
logging:
  pattern: #%class{36}.%M %L
    console: "${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%40.40CML{36}]){cyan} %C#%M:%line %clr(:) %m%n}"
  level:
    root: info
    org.springframework: info


server:
  port: 8081
sqllogging:
  param-abbr-limit: 100
  sql-abbr-limit: 2000
