spring:
  application:
    name: katana-jooq
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
logging:
  level:
    root: info
    org.springframework.web: trace

server:
  port: 8081