/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.naudit.tables;


import com.tengzhe.jooq.data.naudit.Keys;
import com.tengzhe.jooq.data.naudit.Naudit;
import com.tengzhe.jooq.data.naudit.tables.records.UcAccountRecord;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UcAccount extends TableImpl<UcAccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>naudit.uc_account</code>
     */
    public static final UcAccount UC_ACCOUNT = new UcAccount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UcAccountRecord> getRecordType() {
        return UcAccountRecord.class;
    }

    /**
     * The column <code>naudit.uc_account.user_id</code>.
     */
    public final TableField<UcAccountRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>naudit.uc_account.uc_id</code>.
     */
    public final TableField<UcAccountRecord, Long> UC_ID = createField(DSL.name("uc_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>naudit.uc_account.biz_type</code>.
     */
    public final TableField<UcAccountRecord, Integer> BIZ_TYPE = createField(DSL.name("biz_type"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>naudit.uc_account.user_name</code>.
     */
    public final TableField<UcAccountRecord, String> USER_NAME = createField(DSL.name("user_name"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>naudit.uc_account.company_name</code>.
     */
    public final TableField<UcAccountRecord, String> COMPANY_NAME = createField(DSL.name("company_name"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>naudit.uc_account.site_name</code>.
     */
    public final TableField<UcAccountRecord, String> SITE_NAME = createField(DSL.name("site_name"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>naudit.uc_account.site_url</code>.
     */
    public final TableField<UcAccountRecord, String> SITE_URL = createField(DSL.name("site_url"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>naudit.uc_account.site_tag</code>.
     */
    public final TableField<UcAccountRecord, Integer> SITE_TAG = createField(DSL.name("site_tag"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>naudit.uc_account.industry1</code>.
     */
    public final TableField<UcAccountRecord, Integer> INDUSTRY1 = createField(DSL.name("industry1"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>naudit.uc_account.industry2</code>.
     */
    public final TableField<UcAccountRecord, Integer> INDUSTRY2 = createField(DSL.name("industry2"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>naudit.uc_account.industry3</code>.
     */
    public final TableField<UcAccountRecord, Integer> INDUSTRY3 = createField(DSL.name("industry3"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>naudit.uc_account.contact</code>.
     */
    public final TableField<UcAccountRecord, String> CONTACT = createField(DSL.name("contact"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>naudit.uc_account.source</code>.
     */
    public final TableField<UcAccountRecord, Integer> SOURCE = createField(DSL.name("source"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>naudit.uc_account.ad_resource</code>.
     */
    public final TableField<UcAccountRecord, Integer> AD_RESOURCE = createField(DSL.name("ad_resource"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>naudit.uc_account.view_state</code>.
     */
    public final TableField<UcAccountRecord, Integer> VIEW_STATE = createField(DSL.name("view_state"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>naudit.uc_account.finance_state</code>.
     */
    public final TableField<UcAccountRecord, Integer> FINANCE_STATE = createField(DSL.name("finance_state"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>naudit.uc_account.logic_state</code>.
     */
    public final TableField<UcAccountRecord, Integer> LOGIC_STATE = createField(DSL.name("logic_state"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>naudit.uc_account.audit_state</code>.
     */
    public final TableField<UcAccountRecord, Integer> AUDIT_STATE = createField(DSL.name("audit_state"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>naudit.uc_account.auditor_id</code>.
     */
    public final TableField<UcAccountRecord, Long> AUDITOR_ID = createField(DSL.name("auditor_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("-1", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>naudit.uc_account.audit_result</code>.
     */
    public final TableField<UcAccountRecord, String> AUDIT_RESULT = createField(DSL.name("audit_result"), SQLDataType.VARCHAR(1024).nullable(false).defaultValue(DSL.field("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>naudit.uc_account.audit_time</code>.
     */
    public final TableField<UcAccountRecord, LocalDateTime> AUDIT_TIME = createField(DSL.name("audit_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("'9999-12-31 23:59:59'", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>naudit.uc_account.create_time</code>.
     */
    public final TableField<UcAccountRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>naudit.uc_account.modify_time</code>.
     */
    public final TableField<UcAccountRecord, LocalDateTime> MODIFY_TIME = createField(DSL.name("modify_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>naudit.uc_account._flag</code>.
     */
    public final TableField<UcAccountRecord, Integer> _FLAG = createField(DSL.name("_flag"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("1", SQLDataType.INTEGER)), this, "");

    private UcAccount(Name alias, Table<UcAccountRecord> aliased) {
        this(alias, aliased, null);
    }

    private UcAccount(Name alias, Table<UcAccountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>naudit.uc_account</code> table reference
     */
    public UcAccount(String alias) {
        this(DSL.name(alias), UC_ACCOUNT);
    }

    /**
     * Create an aliased <code>naudit.uc_account</code> table reference
     */
    public UcAccount(Name alias) {
        this(alias, UC_ACCOUNT);
    }

    /**
     * Create a <code>naudit.uc_account</code> table reference
     */
    public UcAccount() {
        this(DSL.name("uc_account"), null);
    }

    public <O extends Record> UcAccount(Table<O> child, ForeignKey<O, UcAccountRecord> key) {
        super(child, key, UC_ACCOUNT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Naudit.NAUDIT;
    }

    @Override
    public UniqueKey<UcAccountRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_4;
    }

    @Override
    public UcAccount as(String alias) {
        return new UcAccount(DSL.name(alias), this);
    }

    @Override
    public UcAccount as(Name alias) {
        return new UcAccount(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UcAccount rename(String name) {
        return new UcAccount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UcAccount rename(Name name) {
        return new UcAccount(name, null);
    }
}
