/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.material.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AraHcPvStat implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private Long          creativeId;
    private Integer       adResourceId;
    private Integer       bucketType;
    private Integer       userSource;
    private Integer       pv;
    private Integer       dt;
    private Integer       dimension;
    private LocalDateTime createTime;
    private LocalDateTime modifyTime;

    public AraHcPvStat() {}

    public AraHcPvStat(AraHcPvStat value) {
        this.id = value.id;
        this.creativeId = value.creativeId;
        this.adResourceId = value.adResourceId;
        this.bucketType = value.bucketType;
        this.userSource = value.userSource;
        this.pv = value.pv;
        this.dt = value.dt;
        this.dimension = value.dimension;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
    }

    public AraHcPvStat(
        Long          id,
        Long          creativeId,
        Integer       adResourceId,
        Integer       bucketType,
        Integer       userSource,
        Integer       pv,
        Integer       dt,
        Integer       dimension,
        LocalDateTime createTime,
        LocalDateTime modifyTime
    ) {
        this.id = id;
        this.creativeId = creativeId;
        this.adResourceId = adResourceId;
        this.bucketType = bucketType;
        this.userSource = userSource;
        this.pv = pv;
        this.dt = dt;
        this.dimension = dimension;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }

    /**
     * Getter for <code>material.ara_hc_pv_stat.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>material.ara_hc_pv_stat.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>material.ara_hc_pv_stat.creative_id</code>.
     */
    public Long getCreativeId() {
        return this.creativeId;
    }

    /**
     * Setter for <code>material.ara_hc_pv_stat.creative_id</code>.
     */
    public void setCreativeId(Long creativeId) {
        this.creativeId = creativeId;
    }

    /**
     * Getter for <code>material.ara_hc_pv_stat.ad_resource_id</code>.
     */
    public Integer getAdResourceId() {
        return this.adResourceId;
    }

    /**
     * Setter for <code>material.ara_hc_pv_stat.ad_resource_id</code>.
     */
    public void setAdResourceId(Integer adResourceId) {
        this.adResourceId = adResourceId;
    }

    /**
     * Getter for <code>material.ara_hc_pv_stat.bucket_type</code>.
     */
    public Integer getBucketType() {
        return this.bucketType;
    }

    /**
     * Setter for <code>material.ara_hc_pv_stat.bucket_type</code>.
     */
    public void setBucketType(Integer bucketType) {
        this.bucketType = bucketType;
    }

    /**
     * Getter for <code>material.ara_hc_pv_stat.user_source</code>.
     */
    public Integer getUserSource() {
        return this.userSource;
    }

    /**
     * Setter for <code>material.ara_hc_pv_stat.user_source</code>.
     */
    public void setUserSource(Integer userSource) {
        this.userSource = userSource;
    }

    /**
     * Getter for <code>material.ara_hc_pv_stat.pv</code>.
     */
    public Integer getPv() {
        return this.pv;
    }

    /**
     * Setter for <code>material.ara_hc_pv_stat.pv</code>.
     */
    public void setPv(Integer pv) {
        this.pv = pv;
    }

    /**
     * Getter for <code>material.ara_hc_pv_stat.dt</code>.
     */
    public Integer getDt() {
        return this.dt;
    }

    /**
     * Setter for <code>material.ara_hc_pv_stat.dt</code>.
     */
    public void setDt(Integer dt) {
        this.dt = dt;
    }

    /**
     * Getter for <code>material.ara_hc_pv_stat.dimension</code>.
     */
    public Integer getDimension() {
        return this.dimension;
    }

    /**
     * Setter for <code>material.ara_hc_pv_stat.dimension</code>.
     */
    public void setDimension(Integer dimension) {
        this.dimension = dimension;
    }

    /**
     * Getter for <code>material.ara_hc_pv_stat.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>material.ara_hc_pv_stat.create_time</code>.
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>material.ara_hc_pv_stat.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    /**
     * Setter for <code>material.ara_hc_pv_stat.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AraHcPvStat (");

        sb.append(id);
        sb.append(", ").append(creativeId);
        sb.append(", ").append(adResourceId);
        sb.append(", ").append(bucketType);
        sb.append(", ").append(userSource);
        sb.append(", ").append(pv);
        sb.append(", ").append(dt);
        sb.append(", ").append(dimension);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);

        sb.append(")");
        return sb.toString();
    }
}
