/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.material.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuditRule implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private Integer       entityType;
    private Integer       auditType;
    private String        title;
    private String        description;
    private Integer       state;
    private String        expression;
    private Integer       priority;
    private LocalDateTime createTime;
    private LocalDateTime modifyTime;

    public AuditRule() {}

    public AuditRule(AuditRule value) {
        this.id = value.id;
        this.entityType = value.entityType;
        this.auditType = value.auditType;
        this.title = value.title;
        this.description = value.description;
        this.state = value.state;
        this.expression = value.expression;
        this.priority = value.priority;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
    }

    public AuditRule(
        Long          id,
        Integer       entityType,
        Integer       auditType,
        String        title,
        String        description,
        Integer       state,
        String        expression,
        Integer       priority,
        LocalDateTime createTime,
        LocalDateTime modifyTime
    ) {
        this.id = id;
        this.entityType = entityType;
        this.auditType = auditType;
        this.title = title;
        this.description = description;
        this.state = state;
        this.expression = expression;
        this.priority = priority;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }

    /**
     * Getter for <code>material.audit_rule.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>material.audit_rule.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>material.audit_rule.entity_type</code>.
     */
    public Integer getEntityType() {
        return this.entityType;
    }

    /**
     * Setter for <code>material.audit_rule.entity_type</code>.
     */
    public void setEntityType(Integer entityType) {
        this.entityType = entityType;
    }

    /**
     * Getter for <code>material.audit_rule.audit_type</code>.
     */
    public Integer getAuditType() {
        return this.auditType;
    }

    /**
     * Setter for <code>material.audit_rule.audit_type</code>.
     */
    public void setAuditType(Integer auditType) {
        this.auditType = auditType;
    }

    /**
     * Getter for <code>material.audit_rule.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>material.audit_rule.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>material.audit_rule.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>material.audit_rule.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>material.audit_rule.state</code>.
     */
    public Integer getState() {
        return this.state;
    }

    /**
     * Setter for <code>material.audit_rule.state</code>.
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * Getter for <code>material.audit_rule.expression</code>.
     */
    public String getExpression() {
        return this.expression;
    }

    /**
     * Setter for <code>material.audit_rule.expression</code>.
     */
    public void setExpression(String expression) {
        this.expression = expression;
    }

    /**
     * Getter for <code>material.audit_rule.priority</code>.
     */
    public Integer getPriority() {
        return this.priority;
    }

    /**
     * Setter for <code>material.audit_rule.priority</code>.
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * Getter for <code>material.audit_rule.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>material.audit_rule.create_time</code>.
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>material.audit_rule.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    /**
     * Setter for <code>material.audit_rule.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuditRule (");

        sb.append(id);
        sb.append(", ").append(entityType);
        sb.append(", ").append(auditType);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(state);
        sb.append(", ").append(expression);
        sb.append(", ").append(priority);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);

        sb.append(")");
        return sb.toString();
    }
}
