/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.material.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuditMicroIdeaLogHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private Long          entityId;
    private Long          userId;
    private Integer       type;
    private Integer       adStyleId;
    private String        content;
    private String        libs;
    private Integer       platform;
    private Integer       logicState;
    private Long          version;
    private LocalDateTime submitTime;
    private Integer       state;
    private Integer       stateDetail;
    private String        auditType;
    private String        auditDetail;
    private LocalDateTime createTime;

    public AuditMicroIdeaLogHistory() {}

    public AuditMicroIdeaLogHistory(AuditMicroIdeaLogHistory value) {
        this.id = value.id;
        this.entityId = value.entityId;
        this.userId = value.userId;
        this.type = value.type;
        this.adStyleId = value.adStyleId;
        this.content = value.content;
        this.libs = value.libs;
        this.platform = value.platform;
        this.logicState = value.logicState;
        this.version = value.version;
        this.submitTime = value.submitTime;
        this.state = value.state;
        this.stateDetail = value.stateDetail;
        this.auditType = value.auditType;
        this.auditDetail = value.auditDetail;
        this.createTime = value.createTime;
    }

    public AuditMicroIdeaLogHistory(
        Long          id,
        Long          entityId,
        Long          userId,
        Integer       type,
        Integer       adStyleId,
        String        content,
        String        libs,
        Integer       platform,
        Integer       logicState,
        Long          version,
        LocalDateTime submitTime,
        Integer       state,
        Integer       stateDetail,
        String        auditType,
        String        auditDetail,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.entityId = entityId;
        this.userId = userId;
        this.type = type;
        this.adStyleId = adStyleId;
        this.content = content;
        this.libs = libs;
        this.platform = platform;
        this.logicState = logicState;
        this.version = version;
        this.submitTime = submitTime;
        this.state = state;
        this.stateDetail = stateDetail;
        this.auditType = auditType;
        this.auditDetail = auditDetail;
        this.createTime = createTime;
    }

    /**
     * Getter for <code>material.audit_micro_idea_log_history.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>material.audit_micro_idea_log_history.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>material.audit_micro_idea_log_history.entity_id</code>.
     */
    public Long getEntityId() {
        return this.entityId;
    }

    /**
     * Setter for <code>material.audit_micro_idea_log_history.entity_id</code>.
     */
    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

    /**
     * Getter for <code>material.audit_micro_idea_log_history.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>material.audit_micro_idea_log_history.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>material.audit_micro_idea_log_history.type</code>.
     */
    public Integer getType() {
        return this.type;
    }

    /**
     * Setter for <code>material.audit_micro_idea_log_history.type</code>.
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * Getter for
     * <code>material.audit_micro_idea_log_history.ad_style_id</code>.
     */
    public Integer getAdStyleId() {
        return this.adStyleId;
    }

    /**
     * Setter for
     * <code>material.audit_micro_idea_log_history.ad_style_id</code>.
     */
    public void setAdStyleId(Integer adStyleId) {
        this.adStyleId = adStyleId;
    }

    /**
     * Getter for <code>material.audit_micro_idea_log_history.content</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>material.audit_micro_idea_log_history.content</code>.
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Getter for <code>material.audit_micro_idea_log_history.libs</code>.
     */
    public String getLibs() {
        return this.libs;
    }

    /**
     * Setter for <code>material.audit_micro_idea_log_history.libs</code>.
     */
    public void setLibs(String libs) {
        this.libs = libs;
    }

    /**
     * Getter for <code>material.audit_micro_idea_log_history.platform</code>.
     */
    public Integer getPlatform() {
        return this.platform;
    }

    /**
     * Setter for <code>material.audit_micro_idea_log_history.platform</code>.
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * Getter for
     * <code>material.audit_micro_idea_log_history.logic_state</code>.
     */
    public Integer getLogicState() {
        return this.logicState;
    }

    /**
     * Setter for
     * <code>material.audit_micro_idea_log_history.logic_state</code>.
     */
    public void setLogicState(Integer logicState) {
        this.logicState = logicState;
    }

    /**
     * Getter for <code>material.audit_micro_idea_log_history.version</code>.
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>material.audit_micro_idea_log_history.version</code>.
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * Getter for
     * <code>material.audit_micro_idea_log_history.submit_time</code>.
     */
    public LocalDateTime getSubmitTime() {
        return this.submitTime;
    }

    /**
     * Setter for
     * <code>material.audit_micro_idea_log_history.submit_time</code>.
     */
    public void setSubmitTime(LocalDateTime submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * Getter for <code>material.audit_micro_idea_log_history.state</code>.
     */
    public Integer getState() {
        return this.state;
    }

    /**
     * Setter for <code>material.audit_micro_idea_log_history.state</code>.
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * Getter for
     * <code>material.audit_micro_idea_log_history.state_detail</code>.
     */
    public Integer getStateDetail() {
        return this.stateDetail;
    }

    /**
     * Setter for
     * <code>material.audit_micro_idea_log_history.state_detail</code>.
     */
    public void setStateDetail(Integer stateDetail) {
        this.stateDetail = stateDetail;
    }

    /**
     * Getter for <code>material.audit_micro_idea_log_history.audit_type</code>.
     */
    public String getAuditType() {
        return this.auditType;
    }

    /**
     * Setter for <code>material.audit_micro_idea_log_history.audit_type</code>.
     */
    public void setAuditType(String auditType) {
        this.auditType = auditType;
    }

    /**
     * Getter for
     * <code>material.audit_micro_idea_log_history.audit_detail</code>.
     */
    public String getAuditDetail() {
        return this.auditDetail;
    }

    /**
     * Setter for
     * <code>material.audit_micro_idea_log_history.audit_detail</code>.
     */
    public void setAuditDetail(String auditDetail) {
        this.auditDetail = auditDetail;
    }

    /**
     * Getter for
     * <code>material.audit_micro_idea_log_history.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for
     * <code>material.audit_micro_idea_log_history.create_time</code>.
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuditMicroIdeaLogHistory (");

        sb.append(id);
        sb.append(", ").append(entityId);
        sb.append(", ").append(userId);
        sb.append(", ").append(type);
        sb.append(", ").append(adStyleId);
        sb.append(", ").append(content);
        sb.append(", ").append(libs);
        sb.append(", ").append(platform);
        sb.append(", ").append(logicState);
        sb.append(", ").append(version);
        sb.append(", ").append(submitTime);
        sb.append(", ").append(state);
        sb.append(", ").append(stateDetail);
        sb.append(", ").append(auditType);
        sb.append(", ").append(auditDetail);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
