/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.material.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QualityCheck implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private LocalDateTime sampleDate;
    private Long          userId;
    private String        userName;
    private Integer       checkState;
    private Long          lastCheckerId;
    private String        lastCheckerName;
    private LocalDateTime createTime;
    private LocalDateTime modifyTime;

    public QualityCheck() {}

    public QualityCheck(QualityCheck value) {
        this.id = value.id;
        this.sampleDate = value.sampleDate;
        this.userId = value.userId;
        this.userName = value.userName;
        this.checkState = value.checkState;
        this.lastCheckerId = value.lastCheckerId;
        this.lastCheckerName = value.lastCheckerName;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
    }

    public QualityCheck(
        Long          id,
        LocalDateTime sampleDate,
        Long          userId,
        String        userName,
        Integer       checkState,
        Long          lastCheckerId,
        String        lastCheckerName,
        LocalDateTime createTime,
        LocalDateTime modifyTime
    ) {
        this.id = id;
        this.sampleDate = sampleDate;
        this.userId = userId;
        this.userName = userName;
        this.checkState = checkState;
        this.lastCheckerId = lastCheckerId;
        this.lastCheckerName = lastCheckerName;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }

    /**
     * Getter for <code>material.quality_check.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>material.quality_check.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>material.quality_check.sample_date</code>.
     */
    public LocalDateTime getSampleDate() {
        return this.sampleDate;
    }

    /**
     * Setter for <code>material.quality_check.sample_date</code>.
     */
    public void setSampleDate(LocalDateTime sampleDate) {
        this.sampleDate = sampleDate;
    }

    /**
     * Getter for <code>material.quality_check.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>material.quality_check.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>material.quality_check.user_name</code>.
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>material.quality_check.user_name</code>.
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Getter for <code>material.quality_check.check_state</code>.
     */
    public Integer getCheckState() {
        return this.checkState;
    }

    /**
     * Setter for <code>material.quality_check.check_state</code>.
     */
    public void setCheckState(Integer checkState) {
        this.checkState = checkState;
    }

    /**
     * Getter for <code>material.quality_check.last_checker_id</code>.
     */
    public Long getLastCheckerId() {
        return this.lastCheckerId;
    }

    /**
     * Setter for <code>material.quality_check.last_checker_id</code>.
     */
    public void setLastCheckerId(Long lastCheckerId) {
        this.lastCheckerId = lastCheckerId;
    }

    /**
     * Getter for <code>material.quality_check.last_checker_name</code>.
     */
    public String getLastCheckerName() {
        return this.lastCheckerName;
    }

    /**
     * Setter for <code>material.quality_check.last_checker_name</code>.
     */
    public void setLastCheckerName(String lastCheckerName) {
        this.lastCheckerName = lastCheckerName;
    }

    /**
     * Getter for <code>material.quality_check.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>material.quality_check.create_time</code>.
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>material.quality_check.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    /**
     * Setter for <code>material.quality_check.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QualityCheck (");

        sb.append(id);
        sb.append(", ").append(sampleDate);
        sb.append(", ").append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(checkState);
        sb.append(", ").append(lastCheckerId);
        sb.append(", ").append(lastCheckerName);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);

        sb.append(")");
        return sb.toString();
    }
}
