/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.material.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QualityCheckCampaignSnapshot implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private Long          qualityCheckId;
    private Long          campaignId;
    private String        name;
    private Long          ucId;
    private Long          userId;
    private Long          groupId;
    private Integer       type;
    private Integer       adResourceId;
    private Integer       platform;
    private Long          siteId;
    private String        targetUrl;
    private String        downloadUrl;
    private String        content;
    private Integer       paused;
    private Integer       logicState;
    private Long          version;
    private Integer       state;
    private Integer       stateDetail;
    private LocalDateTime createTime;
    private LocalDateTime modifyTime;

    public QualityCheckCampaignSnapshot() {}

    public QualityCheckCampaignSnapshot(QualityCheckCampaignSnapshot value) {
        this.id = value.id;
        this.qualityCheckId = value.qualityCheckId;
        this.campaignId = value.campaignId;
        this.name = value.name;
        this.ucId = value.ucId;
        this.userId = value.userId;
        this.groupId = value.groupId;
        this.type = value.type;
        this.adResourceId = value.adResourceId;
        this.platform = value.platform;
        this.siteId = value.siteId;
        this.targetUrl = value.targetUrl;
        this.downloadUrl = value.downloadUrl;
        this.content = value.content;
        this.paused = value.paused;
        this.logicState = value.logicState;
        this.version = value.version;
        this.state = value.state;
        this.stateDetail = value.stateDetail;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
    }

    public QualityCheckCampaignSnapshot(
        Long          id,
        Long          qualityCheckId,
        Long          campaignId,
        String        name,
        Long          ucId,
        Long          userId,
        Long          groupId,
        Integer       type,
        Integer       adResourceId,
        Integer       platform,
        Long          siteId,
        String        targetUrl,
        String        downloadUrl,
        String        content,
        Integer       paused,
        Integer       logicState,
        Long          version,
        Integer       state,
        Integer       stateDetail,
        LocalDateTime createTime,
        LocalDateTime modifyTime
    ) {
        this.id = id;
        this.qualityCheckId = qualityCheckId;
        this.campaignId = campaignId;
        this.name = name;
        this.ucId = ucId;
        this.userId = userId;
        this.groupId = groupId;
        this.type = type;
        this.adResourceId = adResourceId;
        this.platform = platform;
        this.siteId = siteId;
        this.targetUrl = targetUrl;
        this.downloadUrl = downloadUrl;
        this.content = content;
        this.paused = paused;
        this.logicState = logicState;
        this.version = version;
        this.state = state;
        this.stateDetail = stateDetail;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }

    /**
     * Getter for <code>material.quality_check_campaign_snapshot.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>material.quality_check_campaign_snapshot.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>material.quality_check_campaign_snapshot.quality_check_id</code>.
     */
    public Long getQualityCheckId() {
        return this.qualityCheckId;
    }

    /**
     * Setter for
     * <code>material.quality_check_campaign_snapshot.quality_check_id</code>.
     */
    public void setQualityCheckId(Long qualityCheckId) {
        this.qualityCheckId = qualityCheckId;
    }

    /**
     * Getter for
     * <code>material.quality_check_campaign_snapshot.campaign_id</code>.
     */
    public Long getCampaignId() {
        return this.campaignId;
    }

    /**
     * Setter for
     * <code>material.quality_check_campaign_snapshot.campaign_id</code>.
     */
    public void setCampaignId(Long campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * Getter for <code>material.quality_check_campaign_snapshot.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>material.quality_check_campaign_snapshot.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>material.quality_check_campaign_snapshot.uc_id</code>.
     */
    public Long getUcId() {
        return this.ucId;
    }

    /**
     * Setter for <code>material.quality_check_campaign_snapshot.uc_id</code>.
     */
    public void setUcId(Long ucId) {
        this.ucId = ucId;
    }

    /**
     * Getter for <code>material.quality_check_campaign_snapshot.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>material.quality_check_campaign_snapshot.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for
     * <code>material.quality_check_campaign_snapshot.group_id</code>.
     */
    public Long getGroupId() {
        return this.groupId;
    }

    /**
     * Setter for
     * <code>material.quality_check_campaign_snapshot.group_id</code>.
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * Getter for <code>material.quality_check_campaign_snapshot.type</code>.
     */
    public Integer getType() {
        return this.type;
    }

    /**
     * Setter for <code>material.quality_check_campaign_snapshot.type</code>.
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * Getter for
     * <code>material.quality_check_campaign_snapshot.ad_resource_id</code>.
     */
    public Integer getAdResourceId() {
        return this.adResourceId;
    }

    /**
     * Setter for
     * <code>material.quality_check_campaign_snapshot.ad_resource_id</code>.
     */
    public void setAdResourceId(Integer adResourceId) {
        this.adResourceId = adResourceId;
    }

    /**
     * Getter for
     * <code>material.quality_check_campaign_snapshot.platform</code>.
     */
    public Integer getPlatform() {
        return this.platform;
    }

    /**
     * Setter for
     * <code>material.quality_check_campaign_snapshot.platform</code>.
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * Getter for <code>material.quality_check_campaign_snapshot.site_id</code>.
     */
    public Long getSiteId() {
        return this.siteId;
    }

    /**
     * Setter for <code>material.quality_check_campaign_snapshot.site_id</code>.
     */
    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    /**
     * Getter for
     * <code>material.quality_check_campaign_snapshot.target_url</code>.
     */
    public String getTargetUrl() {
        return this.targetUrl;
    }

    /**
     * Setter for
     * <code>material.quality_check_campaign_snapshot.target_url</code>.
     */
    public void setTargetUrl(String targetUrl) {
        this.targetUrl = targetUrl;
    }

    /**
     * Getter for
     * <code>material.quality_check_campaign_snapshot.download_url</code>.
     */
    public String getDownloadUrl() {
        return this.downloadUrl;
    }

    /**
     * Setter for
     * <code>material.quality_check_campaign_snapshot.download_url</code>.
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }

    /**
     * Getter for <code>material.quality_check_campaign_snapshot.content</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>material.quality_check_campaign_snapshot.content</code>.
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Getter for <code>material.quality_check_campaign_snapshot.paused</code>.
     */
    public Integer getPaused() {
        return this.paused;
    }

    /**
     * Setter for <code>material.quality_check_campaign_snapshot.paused</code>.
     */
    public void setPaused(Integer paused) {
        this.paused = paused;
    }

    /**
     * Getter for
     * <code>material.quality_check_campaign_snapshot.logic_state</code>.
     */
    public Integer getLogicState() {
        return this.logicState;
    }

    /**
     * Setter for
     * <code>material.quality_check_campaign_snapshot.logic_state</code>.
     */
    public void setLogicState(Integer logicState) {
        this.logicState = logicState;
    }

    /**
     * Getter for <code>material.quality_check_campaign_snapshot.version</code>.
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>material.quality_check_campaign_snapshot.version</code>.
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * Getter for <code>material.quality_check_campaign_snapshot.state</code>.
     */
    public Integer getState() {
        return this.state;
    }

    /**
     * Setter for <code>material.quality_check_campaign_snapshot.state</code>.
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * Getter for
     * <code>material.quality_check_campaign_snapshot.state_detail</code>.
     */
    public Integer getStateDetail() {
        return this.stateDetail;
    }

    /**
     * Setter for
     * <code>material.quality_check_campaign_snapshot.state_detail</code>.
     */
    public void setStateDetail(Integer stateDetail) {
        this.stateDetail = stateDetail;
    }

    /**
     * Getter for
     * <code>material.quality_check_campaign_snapshot.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for
     * <code>material.quality_check_campaign_snapshot.create_time</code>.
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for
     * <code>material.quality_check_campaign_snapshot.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return this.modifyTime;
    }

    /**
     * Setter for
     * <code>material.quality_check_campaign_snapshot.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QualityCheckCampaignSnapshot (");

        sb.append(id);
        sb.append(", ").append(qualityCheckId);
        sb.append(", ").append(campaignId);
        sb.append(", ").append(name);
        sb.append(", ").append(ucId);
        sb.append(", ").append(userId);
        sb.append(", ").append(groupId);
        sb.append(", ").append(type);
        sb.append(", ").append(adResourceId);
        sb.append(", ").append(platform);
        sb.append(", ").append(siteId);
        sb.append(", ").append(targetUrl);
        sb.append(", ").append(downloadUrl);
        sb.append(", ").append(content);
        sb.append(", ").append(paused);
        sb.append(", ").append(logicState);
        sb.append(", ").append(version);
        sb.append(", ").append(state);
        sb.append(", ").append(stateDetail);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);

        sb.append(")");
        return sb.toString();
    }
}
