/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.audit_wolong.tables.records;


import com.tengzhe.jooq.data.audit_wolong.tables.AuditExcludeWord;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuditExcludeWordRecord extends UpdatableRecordImpl<AuditExcludeWordRecord> implements Record5<Integer, String, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>audit_wolong.audit_exclude_word.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>audit_wolong.audit_exclude_word.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>audit_wolong.audit_exclude_word.word</code>.
     */
    public void setWord(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>audit_wolong.audit_exclude_word.word</code>.
     */
    public String getWord() {
        return (String) get(1);
    }

    /**
     * Setter for <code>audit_wolong.audit_exclude_word.targetid</code>.
     */
    public void setTargetid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>audit_wolong.audit_exclude_word.targetid</code>.
     */
    public Integer getTargetid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>audit_wolong.audit_exclude_word.word_type</code>.
     */
    public void setWordType(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>audit_wolong.audit_exclude_word.word_type</code>.
     */
    public Integer getWordType() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>audit_wolong.audit_exclude_word.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>audit_wolong.audit_exclude_word.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AuditExcludeWord.AUDIT_EXCLUDE_WORD.ID;
    }

    @Override
    public Field<String> field2() {
        return AuditExcludeWord.AUDIT_EXCLUDE_WORD.WORD;
    }

    @Override
    public Field<Integer> field3() {
        return AuditExcludeWord.AUDIT_EXCLUDE_WORD.TARGETID;
    }

    @Override
    public Field<Integer> field4() {
        return AuditExcludeWord.AUDIT_EXCLUDE_WORD.WORD_TYPE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return AuditExcludeWord.AUDIT_EXCLUDE_WORD.CREATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getWord();
    }

    @Override
    public Integer component3() {
        return getTargetid();
    }

    @Override
    public Integer component4() {
        return getWordType();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getWord();
    }

    @Override
    public Integer value3() {
        return getTargetid();
    }

    @Override
    public Integer value4() {
        return getWordType();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public AuditExcludeWordRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AuditExcludeWordRecord value2(String value) {
        setWord(value);
        return this;
    }

    @Override
    public AuditExcludeWordRecord value3(Integer value) {
        setTargetid(value);
        return this;
    }

    @Override
    public AuditExcludeWordRecord value4(Integer value) {
        setWordType(value);
        return this;
    }

    @Override
    public AuditExcludeWordRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public AuditExcludeWordRecord values(Integer value1, String value2, Integer value3, Integer value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuditExcludeWordRecord
     */
    public AuditExcludeWordRecord() {
        super(AuditExcludeWord.AUDIT_EXCLUDE_WORD);
    }

    /**
     * Create a detached, initialised AuditExcludeWordRecord
     */
    public AuditExcludeWordRecord(Integer id, String word, Integer targetid, Integer wordType, LocalDateTime createTime) {
        super(AuditExcludeWord.AUDIT_EXCLUDE_WORD);

        setId(id);
        setWord(word);
        setTargetid(targetid);
        setWordType(wordType);
        setCreateTime(createTime);
    }

    /**
     * Create a detached, initialised AuditExcludeWordRecord
     */
    public AuditExcludeWordRecord(com.tengzhe.jooq.data.audit_wolong.tables.pojos.AuditExcludeWord value) {
        super(AuditExcludeWord.AUDIT_EXCLUDE_WORD);

        if (value != null) {
            setId(value.getId());
            setWord(value.getWord());
            setTargetid(value.getTargetid());
            setWordType(value.getWordType());
            setCreateTime(value.getCreateTime());
        }
    }
}
