/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.audit_wolong.tables.records;


import com.tengzhe.jooq.data.audit_wolong.tables.AuditUnitMaterial;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuditUnitMaterialRecord extends UpdatableRecordImpl<AuditUnitMaterialRecord> implements Record7<Long, Long, Long, Long, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>audit_wolong.audit_unit_material.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>audit_wolong.audit_unit_material.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>audit_wolong.audit_unit_material.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>audit_wolong.audit_unit_material.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>audit_wolong.audit_unit_material.unit_id</code>.
     */
    public void setUnitId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>audit_wolong.audit_unit_material.unit_id</code>.
     */
    public Long getUnitId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>audit_wolong.audit_unit_material.auditor_id</code>.
     */
    public void setAuditorId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>audit_wolong.audit_unit_material.auditor_id</code>.
     */
    public Long getAuditorId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>audit_wolong.audit_unit_material.unit_time</code>.
     */
    public void setUnitTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>audit_wolong.audit_unit_material.unit_time</code>.
     */
    public LocalDateTime getUnitTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>audit_wolong.audit_unit_material.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>audit_wolong.audit_unit_material.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>audit_wolong.audit_unit_material.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>audit_wolong.audit_unit_material.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, Long, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Long, Long, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AuditUnitMaterial.AUDIT_UNIT_MATERIAL.ID;
    }

    @Override
    public Field<Long> field2() {
        return AuditUnitMaterial.AUDIT_UNIT_MATERIAL.USER_ID;
    }

    @Override
    public Field<Long> field3() {
        return AuditUnitMaterial.AUDIT_UNIT_MATERIAL.UNIT_ID;
    }

    @Override
    public Field<Long> field4() {
        return AuditUnitMaterial.AUDIT_UNIT_MATERIAL.AUDITOR_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return AuditUnitMaterial.AUDIT_UNIT_MATERIAL.UNIT_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return AuditUnitMaterial.AUDIT_UNIT_MATERIAL.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return AuditUnitMaterial.AUDIT_UNIT_MATERIAL.MODIFY_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Long component3() {
        return getUnitId();
    }

    @Override
    public Long component4() {
        return getAuditorId();
    }

    @Override
    public LocalDateTime component5() {
        return getUnitTime();
    }

    @Override
    public LocalDateTime component6() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component7() {
        return getModifyTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public Long value3() {
        return getUnitId();
    }

    @Override
    public Long value4() {
        return getAuditorId();
    }

    @Override
    public LocalDateTime value5() {
        return getUnitTime();
    }

    @Override
    public LocalDateTime value6() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value7() {
        return getModifyTime();
    }

    @Override
    public AuditUnitMaterialRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AuditUnitMaterialRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public AuditUnitMaterialRecord value3(Long value) {
        setUnitId(value);
        return this;
    }

    @Override
    public AuditUnitMaterialRecord value4(Long value) {
        setAuditorId(value);
        return this;
    }

    @Override
    public AuditUnitMaterialRecord value5(LocalDateTime value) {
        setUnitTime(value);
        return this;
    }

    @Override
    public AuditUnitMaterialRecord value6(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public AuditUnitMaterialRecord value7(LocalDateTime value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public AuditUnitMaterialRecord values(Long value1, Long value2, Long value3, Long value4, LocalDateTime value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuditUnitMaterialRecord
     */
    public AuditUnitMaterialRecord() {
        super(AuditUnitMaterial.AUDIT_UNIT_MATERIAL);
    }

    /**
     * Create a detached, initialised AuditUnitMaterialRecord
     */
    public AuditUnitMaterialRecord(Long id, Long userId, Long unitId, Long auditorId, LocalDateTime unitTime, LocalDateTime createTime, LocalDateTime modifyTime) {
        super(AuditUnitMaterial.AUDIT_UNIT_MATERIAL);

        setId(id);
        setUserId(userId);
        setUnitId(unitId);
        setAuditorId(auditorId);
        setUnitTime(unitTime);
        setCreateTime(createTime);
        setModifyTime(modifyTime);
    }

    /**
     * Create a detached, initialised AuditUnitMaterialRecord
     */
    public AuditUnitMaterialRecord(com.tengzhe.jooq.data.audit_wolong.tables.pojos.AuditUnitMaterial value) {
        super(AuditUnitMaterial.AUDIT_UNIT_MATERIAL);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setUnitId(value.getUnitId());
            setAuditorId(value.getAuditorId());
            setUnitTime(value.getUnitTime());
            setCreateTime(value.getCreateTime());
            setModifyTime(value.getModifyTime());
        }
    }
}
