/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.audit_wolong.tables.records;


import com.tengzhe.jooq.data.audit_wolong.tables.PictureLib;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PictureLibRecord extends UpdatableRecordImpl<PictureLibRecord> implements Record6<Long, Long, Long, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>audit_wolong.picture_lib.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>audit_wolong.picture_lib.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>audit_wolong.picture_lib.userid</code>.
     */
    public void setUserid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>audit_wolong.picture_lib.userid</code>.
     */
    public Long getUserid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>audit_wolong.picture_lib.version</code>.
     */
    public void setVersion(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>audit_wolong.picture_lib.version</code>.
     */
    public Long getVersion() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>audit_wolong.picture_lib.image_url</code>.
     */
    public void setImageUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>audit_wolong.picture_lib.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>audit_wolong.picture_lib.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>audit_wolong.picture_lib.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>audit_wolong.picture_lib.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>audit_wolong.picture_lib.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PictureLib.PICTURE_LIB.ID;
    }

    @Override
    public Field<Long> field2() {
        return PictureLib.PICTURE_LIB.USERID;
    }

    @Override
    public Field<Long> field3() {
        return PictureLib.PICTURE_LIB.VERSION;
    }

    @Override
    public Field<String> field4() {
        return PictureLib.PICTURE_LIB.IMAGE_URL;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return PictureLib.PICTURE_LIB.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return PictureLib.PICTURE_LIB.MODIFY_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserid();
    }

    @Override
    public Long component3() {
        return getVersion();
    }

    @Override
    public String component4() {
        return getImageUrl();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component6() {
        return getModifyTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserid();
    }

    @Override
    public Long value3() {
        return getVersion();
    }

    @Override
    public String value4() {
        return getImageUrl();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value6() {
        return getModifyTime();
    }

    @Override
    public PictureLibRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PictureLibRecord value2(Long value) {
        setUserid(value);
        return this;
    }

    @Override
    public PictureLibRecord value3(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public PictureLibRecord value4(String value) {
        setImageUrl(value);
        return this;
    }

    @Override
    public PictureLibRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public PictureLibRecord value6(LocalDateTime value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public PictureLibRecord values(Long value1, Long value2, Long value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PictureLibRecord
     */
    public PictureLibRecord() {
        super(PictureLib.PICTURE_LIB);
    }

    /**
     * Create a detached, initialised PictureLibRecord
     */
    public PictureLibRecord(Long id, Long userid, Long version, String imageUrl, LocalDateTime createTime, LocalDateTime modifyTime) {
        super(PictureLib.PICTURE_LIB);

        setId(id);
        setUserid(userid);
        setVersion(version);
        setImageUrl(imageUrl);
        setCreateTime(createTime);
        setModifyTime(modifyTime);
    }

    /**
     * Create a detached, initialised PictureLibRecord
     */
    public PictureLibRecord(com.tengzhe.jooq.data.audit_wolong.tables.pojos.PictureLib value) {
        super(PictureLib.PICTURE_LIB);

        if (value != null) {
            setId(value.getId());
            setUserid(value.getUserid());
            setVersion(value.getVersion());
            setImageUrl(value.getImageUrl());
            setCreateTime(value.getCreateTime());
            setModifyTime(value.getModifyTime());
        }
    }
}
