/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.audit_wolong.tables.records;


import com.tengzhe.jooq.data.audit_wolong.tables.UcAccount;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UcAccountRecord extends UpdatableRecordImpl<UcAccountRecord> implements Record19<Long, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, String, Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>audit_wolong.uc_account.userid</code>.
     */
    public void setUserid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.userid</code>.
     */
    public Long getUserid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.user_name</code>.
     */
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.user_name</code>.
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.nick_name</code>.
     */
    public void setNickName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.nick_name</code>.
     */
    public String getNickName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.industry1</code>.
     */
    public void setIndustry1(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.industry1</code>.
     */
    public Integer getIndustry1() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.industry2</code>.
     */
    public void setIndustry2(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.industry2</code>.
     */
    public Integer getIndustry2() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.industry3</code>.
     */
    public void setIndustry3(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.industry3</code>.
     */
    public Integer getIndustry3() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.account_type</code>.
     */
    public void setAccountType(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.account_type</code>.
     */
    public Integer getAccountType() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.review_state</code>.
     */
    public void setReviewState(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.review_state</code>.
     */
    public Integer getReviewState() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.finance_state</code>.
     */
    public void setFinanceState(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.finance_state</code>.
     */
    public Integer getFinanceState() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.view_state</code>.
     */
    public void setViewState(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.view_state</code>.
     */
    public Integer getViewState() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.group_name</code>.
     */
    public void setGroupName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.group_name</code>.
     */
    public String getGroupName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.roles</code>.
     */
    public void setRoles(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.roles</code>.
     */
    public String getRoles() {
        return (String) get(11);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.source</code>.
     */
    public void setSource(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.source</code>.
     */
    public Integer getSource() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.first_recharge_time</code>.
     */
    public void setFirstRechargeTime(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.first_recharge_time</code>.
     */
    public LocalDateTime getFirstRechargeTime() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.last_login_time</code>.
     */
    public void setLastLoginTime(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.last_login_time</code>.
     */
    public LocalDateTime getLastLoginTime() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.first_available_time</code>.
     */
    public void setFirstAvailableTime(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.first_available_time</code>.
     */
    public LocalDateTime getFirstAvailableTime() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>audit_wolong.uc_account.deleted</code>.
     */
    public void setDeleted(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>audit_wolong.uc_account.deleted</code>.
     */
    public Integer getDeleted() {
        return (Integer) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<Long, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, String, Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<Long, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, String, Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UcAccount.UC_ACCOUNT.USERID;
    }

    @Override
    public Field<String> field2() {
        return UcAccount.UC_ACCOUNT.USER_NAME;
    }

    @Override
    public Field<String> field3() {
        return UcAccount.UC_ACCOUNT.NICK_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return UcAccount.UC_ACCOUNT.INDUSTRY1;
    }

    @Override
    public Field<Integer> field5() {
        return UcAccount.UC_ACCOUNT.INDUSTRY2;
    }

    @Override
    public Field<Integer> field6() {
        return UcAccount.UC_ACCOUNT.INDUSTRY3;
    }

    @Override
    public Field<Integer> field7() {
        return UcAccount.UC_ACCOUNT.ACCOUNT_TYPE;
    }

    @Override
    public Field<Integer> field8() {
        return UcAccount.UC_ACCOUNT.REVIEW_STATE;
    }

    @Override
    public Field<Integer> field9() {
        return UcAccount.UC_ACCOUNT.FINANCE_STATE;
    }

    @Override
    public Field<Integer> field10() {
        return UcAccount.UC_ACCOUNT.VIEW_STATE;
    }

    @Override
    public Field<String> field11() {
        return UcAccount.UC_ACCOUNT.GROUP_NAME;
    }

    @Override
    public Field<String> field12() {
        return UcAccount.UC_ACCOUNT.ROLES;
    }

    @Override
    public Field<Integer> field13() {
        return UcAccount.UC_ACCOUNT.SOURCE;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return UcAccount.UC_ACCOUNT.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return UcAccount.UC_ACCOUNT.MODIFY_TIME;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return UcAccount.UC_ACCOUNT.FIRST_RECHARGE_TIME;
    }

    @Override
    public Field<LocalDateTime> field17() {
        return UcAccount.UC_ACCOUNT.LAST_LOGIN_TIME;
    }

    @Override
    public Field<LocalDateTime> field18() {
        return UcAccount.UC_ACCOUNT.FIRST_AVAILABLE_TIME;
    }

    @Override
    public Field<Integer> field19() {
        return UcAccount.UC_ACCOUNT.DELETED;
    }

    @Override
    public Long component1() {
        return getUserid();
    }

    @Override
    public String component2() {
        return getUserName();
    }

    @Override
    public String component3() {
        return getNickName();
    }

    @Override
    public Integer component4() {
        return getIndustry1();
    }

    @Override
    public Integer component5() {
        return getIndustry2();
    }

    @Override
    public Integer component6() {
        return getIndustry3();
    }

    @Override
    public Integer component7() {
        return getAccountType();
    }

    @Override
    public Integer component8() {
        return getReviewState();
    }

    @Override
    public Integer component9() {
        return getFinanceState();
    }

    @Override
    public Integer component10() {
        return getViewState();
    }

    @Override
    public String component11() {
        return getGroupName();
    }

    @Override
    public String component12() {
        return getRoles();
    }

    @Override
    public Integer component13() {
        return getSource();
    }

    @Override
    public LocalDateTime component14() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component15() {
        return getModifyTime();
    }

    @Override
    public LocalDateTime component16() {
        return getFirstRechargeTime();
    }

    @Override
    public LocalDateTime component17() {
        return getLastLoginTime();
    }

    @Override
    public LocalDateTime component18() {
        return getFirstAvailableTime();
    }

    @Override
    public Integer component19() {
        return getDeleted();
    }

    @Override
    public Long value1() {
        return getUserid();
    }

    @Override
    public String value2() {
        return getUserName();
    }

    @Override
    public String value3() {
        return getNickName();
    }

    @Override
    public Integer value4() {
        return getIndustry1();
    }

    @Override
    public Integer value5() {
        return getIndustry2();
    }

    @Override
    public Integer value6() {
        return getIndustry3();
    }

    @Override
    public Integer value7() {
        return getAccountType();
    }

    @Override
    public Integer value8() {
        return getReviewState();
    }

    @Override
    public Integer value9() {
        return getFinanceState();
    }

    @Override
    public Integer value10() {
        return getViewState();
    }

    @Override
    public String value11() {
        return getGroupName();
    }

    @Override
    public String value12() {
        return getRoles();
    }

    @Override
    public Integer value13() {
        return getSource();
    }

    @Override
    public LocalDateTime value14() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value15() {
        return getModifyTime();
    }

    @Override
    public LocalDateTime value16() {
        return getFirstRechargeTime();
    }

    @Override
    public LocalDateTime value17() {
        return getLastLoginTime();
    }

    @Override
    public LocalDateTime value18() {
        return getFirstAvailableTime();
    }

    @Override
    public Integer value19() {
        return getDeleted();
    }

    @Override
    public UcAccountRecord value1(Long value) {
        setUserid(value);
        return this;
    }

    @Override
    public UcAccountRecord value2(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public UcAccountRecord value3(String value) {
        setNickName(value);
        return this;
    }

    @Override
    public UcAccountRecord value4(Integer value) {
        setIndustry1(value);
        return this;
    }

    @Override
    public UcAccountRecord value5(Integer value) {
        setIndustry2(value);
        return this;
    }

    @Override
    public UcAccountRecord value6(Integer value) {
        setIndustry3(value);
        return this;
    }

    @Override
    public UcAccountRecord value7(Integer value) {
        setAccountType(value);
        return this;
    }

    @Override
    public UcAccountRecord value8(Integer value) {
        setReviewState(value);
        return this;
    }

    @Override
    public UcAccountRecord value9(Integer value) {
        setFinanceState(value);
        return this;
    }

    @Override
    public UcAccountRecord value10(Integer value) {
        setViewState(value);
        return this;
    }

    @Override
    public UcAccountRecord value11(String value) {
        setGroupName(value);
        return this;
    }

    @Override
    public UcAccountRecord value12(String value) {
        setRoles(value);
        return this;
    }

    @Override
    public UcAccountRecord value13(Integer value) {
        setSource(value);
        return this;
    }

    @Override
    public UcAccountRecord value14(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public UcAccountRecord value15(LocalDateTime value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public UcAccountRecord value16(LocalDateTime value) {
        setFirstRechargeTime(value);
        return this;
    }

    @Override
    public UcAccountRecord value17(LocalDateTime value) {
        setLastLoginTime(value);
        return this;
    }

    @Override
    public UcAccountRecord value18(LocalDateTime value) {
        setFirstAvailableTime(value);
        return this;
    }

    @Override
    public UcAccountRecord value19(Integer value) {
        setDeleted(value);
        return this;
    }

    @Override
    public UcAccountRecord values(Long value1, String value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10, String value11, String value12, Integer value13, LocalDateTime value14, LocalDateTime value15, LocalDateTime value16, LocalDateTime value17, LocalDateTime value18, Integer value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UcAccountRecord
     */
    public UcAccountRecord() {
        super(UcAccount.UC_ACCOUNT);
    }

    /**
     * Create a detached, initialised UcAccountRecord
     */
    public UcAccountRecord(Long userid, String userName, String nickName, Integer industry1, Integer industry2, Integer industry3, Integer accountType, Integer reviewState, Integer financeState, Integer viewState, String groupName, String roles, Integer source, LocalDateTime createTime, LocalDateTime modifyTime, LocalDateTime firstRechargeTime, LocalDateTime lastLoginTime, LocalDateTime firstAvailableTime, Integer deleted) {
        super(UcAccount.UC_ACCOUNT);

        setUserid(userid);
        setUserName(userName);
        setNickName(nickName);
        setIndustry1(industry1);
        setIndustry2(industry2);
        setIndustry3(industry3);
        setAccountType(accountType);
        setReviewState(reviewState);
        setFinanceState(financeState);
        setViewState(viewState);
        setGroupName(groupName);
        setRoles(roles);
        setSource(source);
        setCreateTime(createTime);
        setModifyTime(modifyTime);
        setFirstRechargeTime(firstRechargeTime);
        setLastLoginTime(lastLoginTime);
        setFirstAvailableTime(firstAvailableTime);
        setDeleted(deleted);
    }

    /**
     * Create a detached, initialised UcAccountRecord
     */
    public UcAccountRecord(com.tengzhe.jooq.data.audit_wolong.tables.pojos.UcAccount value) {
        super(UcAccount.UC_ACCOUNT);

        if (value != null) {
            setUserid(value.getUserid());
            setUserName(value.getUserName());
            setNickName(value.getNickName());
            setIndustry1(value.getIndustry1());
            setIndustry2(value.getIndustry2());
            setIndustry3(value.getIndustry3());
            setAccountType(value.getAccountType());
            setReviewState(value.getReviewState());
            setFinanceState(value.getFinanceState());
            setViewState(value.getViewState());
            setGroupName(value.getGroupName());
            setRoles(value.getRoles());
            setSource(value.getSource());
            setCreateTime(value.getCreateTime());
            setModifyTime(value.getModifyTime());
            setFirstRechargeTime(value.getFirstRechargeTime());
            setLastLoginTime(value.getLastLoginTime());
            setFirstAvailableTime(value.getFirstAvailableTime());
            setDeleted(value.getDeleted());
        }
    }
}
