/*
 * This file is generated by jOOQ.
 */
package com.katana.jooq.entity.uc;


import com.katana.jooq.entity.uc.tables.Account;
import com.katana.jooq.entity.uc.tables.records.AccountRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in uc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> CONSTRAINT_B = Internal.createUniqueKey(Account.ACCOUNT, DSL.name("CONSTRAINT_B"), new TableField[] { Account.ACCOUNT.ID }, true);
}
