/*
 * This file is generated by jOOQ.
 */
package com.katana.jooq.entity.uc;


import com.katana.jooq.entity.uc.tables.Account;


/**
 * Convenience access to all tables in uc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>uc.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;
}
