/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.naudit.tables.records;


import com.tengzhe.jooq.data.naudit.tables.AraIllegalClue;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AraIllegalClueRecord extends UpdatableRecordImpl<AraIllegalClueRecord> implements Record10<Long, String, String, LocalDateTime, String, Long, Long, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>naudit.ara_illegal_clue.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>naudit.ara_illegal_clue.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>naudit.ara_illegal_clue.clue_no</code>.
     */
    public void setClueNo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>naudit.ara_illegal_clue.clue_no</code>.
     */
    public String getClueNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>naudit.ara_illegal_clue.clue_url</code>.
     */
    public void setClueUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>naudit.ara_illegal_clue.clue_url</code>.
     */
    public String getClueUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>naudit.ara_illegal_clue.clue_time</code>.
     */
    public void setClueTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>naudit.ara_illegal_clue.clue_time</code>.
     */
    public LocalDateTime getClueTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>naudit.ara_illegal_clue.ad_url</code>.
     */
    public void setAdUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>naudit.ara_illegal_clue.ad_url</code>.
     */
    public String getAdUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>naudit.ara_illegal_clue.user_id</code>.
     */
    public void setUserId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>naudit.ara_illegal_clue.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>naudit.ara_illegal_clue.state</code>.
     */
    public void setState(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>naudit.ara_illegal_clue.state</code>.
     */
    public Long getState() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>naudit.ara_illegal_clue.biz_type</code>.
     */
    public void setBizType(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>naudit.ara_illegal_clue.biz_type</code>.
     */
    public Integer getBizType() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>naudit.ara_illegal_clue.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>naudit.ara_illegal_clue.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>naudit.ara_illegal_clue.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>naudit.ara_illegal_clue.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, LocalDateTime, String, Long, Long, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, LocalDateTime, String, Long, Long, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AraIllegalClue.ARA_ILLEGAL_CLUE.ID;
    }

    @Override
    public Field<String> field2() {
        return AraIllegalClue.ARA_ILLEGAL_CLUE.CLUE_NO;
    }

    @Override
    public Field<String> field3() {
        return AraIllegalClue.ARA_ILLEGAL_CLUE.CLUE_URL;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return AraIllegalClue.ARA_ILLEGAL_CLUE.CLUE_TIME;
    }

    @Override
    public Field<String> field5() {
        return AraIllegalClue.ARA_ILLEGAL_CLUE.AD_URL;
    }

    @Override
    public Field<Long> field6() {
        return AraIllegalClue.ARA_ILLEGAL_CLUE.USER_ID;
    }

    @Override
    public Field<Long> field7() {
        return AraIllegalClue.ARA_ILLEGAL_CLUE.STATE;
    }

    @Override
    public Field<Integer> field8() {
        return AraIllegalClue.ARA_ILLEGAL_CLUE.BIZ_TYPE;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return AraIllegalClue.ARA_ILLEGAL_CLUE.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return AraIllegalClue.ARA_ILLEGAL_CLUE.MODIFY_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getClueNo();
    }

    @Override
    public String component3() {
        return getClueUrl();
    }

    @Override
    public LocalDateTime component4() {
        return getClueTime();
    }

    @Override
    public String component5() {
        return getAdUrl();
    }

    @Override
    public Long component6() {
        return getUserId();
    }

    @Override
    public Long component7() {
        return getState();
    }

    @Override
    public Integer component8() {
        return getBizType();
    }

    @Override
    public LocalDateTime component9() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component10() {
        return getModifyTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getClueNo();
    }

    @Override
    public String value3() {
        return getClueUrl();
    }

    @Override
    public LocalDateTime value4() {
        return getClueTime();
    }

    @Override
    public String value5() {
        return getAdUrl();
    }

    @Override
    public Long value6() {
        return getUserId();
    }

    @Override
    public Long value7() {
        return getState();
    }

    @Override
    public Integer value8() {
        return getBizType();
    }

    @Override
    public LocalDateTime value9() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value10() {
        return getModifyTime();
    }

    @Override
    public AraIllegalClueRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AraIllegalClueRecord value2(String value) {
        setClueNo(value);
        return this;
    }

    @Override
    public AraIllegalClueRecord value3(String value) {
        setClueUrl(value);
        return this;
    }

    @Override
    public AraIllegalClueRecord value4(LocalDateTime value) {
        setClueTime(value);
        return this;
    }

    @Override
    public AraIllegalClueRecord value5(String value) {
        setAdUrl(value);
        return this;
    }

    @Override
    public AraIllegalClueRecord value6(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public AraIllegalClueRecord value7(Long value) {
        setState(value);
        return this;
    }

    @Override
    public AraIllegalClueRecord value8(Integer value) {
        setBizType(value);
        return this;
    }

    @Override
    public AraIllegalClueRecord value9(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public AraIllegalClueRecord value10(LocalDateTime value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public AraIllegalClueRecord values(Long value1, String value2, String value3, LocalDateTime value4, String value5, Long value6, Long value7, Integer value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AraIllegalClueRecord
     */
    public AraIllegalClueRecord() {
        super(AraIllegalClue.ARA_ILLEGAL_CLUE);
    }

    /**
     * Create a detached, initialised AraIllegalClueRecord
     */
    public AraIllegalClueRecord(Long id, String clueNo, String clueUrl, LocalDateTime clueTime, String adUrl, Long userId, Long state, Integer bizType, LocalDateTime createTime, LocalDateTime modifyTime) {
        super(AraIllegalClue.ARA_ILLEGAL_CLUE);

        setId(id);
        setClueNo(clueNo);
        setClueUrl(clueUrl);
        setClueTime(clueTime);
        setAdUrl(adUrl);
        setUserId(userId);
        setState(state);
        setBizType(bizType);
        setCreateTime(createTime);
        setModifyTime(modifyTime);
    }

    /**
     * Create a detached, initialised AraIllegalClueRecord
     */
    public AraIllegalClueRecord(com.tengzhe.jooq.data.naudit.tables.pojos.AraIllegalClue value) {
        super(AraIllegalClue.ARA_ILLEGAL_CLUE);

        if (value != null) {
            setId(value.getId());
            setClueNo(value.getClueNo());
            setClueUrl(value.getClueUrl());
            setClueTime(value.getClueTime());
            setAdUrl(value.getAdUrl());
            setUserId(value.getUserId());
            setState(value.getState());
            setBizType(value.getBizType());
            setCreateTime(value.getCreateTime());
            setModifyTime(value.getModifyTime());
        }
    }
}
