/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.naudit.tables.records;


import com.tengzhe.jooq.data.naudit.tables.UcRelation;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UcRelationRecord extends UpdatableRecordImpl<UcRelationRecord> implements Record8<Long, Long, String, Integer, Long, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>naudit.uc_relation.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>naudit.uc_relation.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>naudit.uc_relation.uc_id</code>.
     */
    public void setUcId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>naudit.uc_relation.uc_id</code>.
     */
    public Long getUcId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>naudit.uc_relation.user_name</code>.
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>naudit.uc_relation.user_name</code>.
     */
    public String getUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>naudit.uc_relation.type</code>.
     */
    public void setType(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>naudit.uc_relation.type</code>.
     */
    public Integer getType() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>naudit.uc_relation.target_id</code>.
     */
    public void setTargetId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>naudit.uc_relation.target_id</code>.
     */
    public Long getTargetId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>naudit.uc_relation.target_name</code>.
     */
    public void setTargetName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>naudit.uc_relation.target_name</code>.
     */
    public String getTargetName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>naudit.uc_relation.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>naudit.uc_relation.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>naudit.uc_relation.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>naudit.uc_relation.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, String, Integer, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, String, Integer, Long, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UcRelation.UC_RELATION.ID;
    }

    @Override
    public Field<Long> field2() {
        return UcRelation.UC_RELATION.UC_ID;
    }

    @Override
    public Field<String> field3() {
        return UcRelation.UC_RELATION.USER_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return UcRelation.UC_RELATION.TYPE;
    }

    @Override
    public Field<Long> field5() {
        return UcRelation.UC_RELATION.TARGET_ID;
    }

    @Override
    public Field<String> field6() {
        return UcRelation.UC_RELATION.TARGET_NAME;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return UcRelation.UC_RELATION.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return UcRelation.UC_RELATION.MODIFY_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUcId();
    }

    @Override
    public String component3() {
        return getUserName();
    }

    @Override
    public Integer component4() {
        return getType();
    }

    @Override
    public Long component5() {
        return getTargetId();
    }

    @Override
    public String component6() {
        return getTargetName();
    }

    @Override
    public LocalDateTime component7() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component8() {
        return getModifyTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUcId();
    }

    @Override
    public String value3() {
        return getUserName();
    }

    @Override
    public Integer value4() {
        return getType();
    }

    @Override
    public Long value5() {
        return getTargetId();
    }

    @Override
    public String value6() {
        return getTargetName();
    }

    @Override
    public LocalDateTime value7() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value8() {
        return getModifyTime();
    }

    @Override
    public UcRelationRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UcRelationRecord value2(Long value) {
        setUcId(value);
        return this;
    }

    @Override
    public UcRelationRecord value3(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public UcRelationRecord value4(Integer value) {
        setType(value);
        return this;
    }

    @Override
    public UcRelationRecord value5(Long value) {
        setTargetId(value);
        return this;
    }

    @Override
    public UcRelationRecord value6(String value) {
        setTargetName(value);
        return this;
    }

    @Override
    public UcRelationRecord value7(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public UcRelationRecord value8(LocalDateTime value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public UcRelationRecord values(Long value1, Long value2, String value3, Integer value4, Long value5, String value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UcRelationRecord
     */
    public UcRelationRecord() {
        super(UcRelation.UC_RELATION);
    }

    /**
     * Create a detached, initialised UcRelationRecord
     */
    public UcRelationRecord(Long id, Long ucId, String userName, Integer type, Long targetId, String targetName, LocalDateTime createTime, LocalDateTime modifyTime) {
        super(UcRelation.UC_RELATION);

        setId(id);
        setUcId(ucId);
        setUserName(userName);
        setType(type);
        setTargetId(targetId);
        setTargetName(targetName);
        setCreateTime(createTime);
        setModifyTime(modifyTime);
    }

    /**
     * Create a detached, initialised UcRelationRecord
     */
    public UcRelationRecord(com.tengzhe.jooq.data.naudit.tables.pojos.UcRelation value) {
        super(UcRelation.UC_RELATION);

        if (value != null) {
            setId(value.getId());
            setUcId(value.getUcId());
            setUserName(value.getUserName());
            setType(value.getType());
            setTargetId(value.getTargetId());
            setTargetName(value.getTargetName());
            setCreateTime(value.getCreateTime());
            setModifyTime(value.getModifyTime());
        }
    }
}
