/*
 * This file is generated by jOOQ.
 */
package com.tengzhe.jooq.data.naudit.tables.records;


import com.tengzhe.jooq.data.naudit.tables.UrlSnapshot;

import java.util.Date;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UrlSnapshotRecord extends UpdatableRecordImpl<UrlSnapshotRecord> implements Record4<Long, String, String, Date> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>naudit.url_snapshot.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>naudit.url_snapshot.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>naudit.url_snapshot.url</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>naudit.url_snapshot.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>naudit.url_snapshot.screen_shot_url</code>.
     */
    public void setScreenShotUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>naudit.url_snapshot.screen_shot_url</code>.
     */
    public String getScreenShotUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>naudit.url_snapshot.crawl_time</code>.
     */
    public void setCrawlTime(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>naudit.url_snapshot.crawl_time</code>.
     */
    public Date getCrawlTime() {
        return (Date) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Date> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, Date> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UrlSnapshot.URL_SNAPSHOT.ID;
    }

    @Override
    public Field<String> field2() {
        return UrlSnapshot.URL_SNAPSHOT.URL;
    }

    @Override
    public Field<String> field3() {
        return UrlSnapshot.URL_SNAPSHOT.SCREEN_SHOT_URL;
    }

    @Override
    public Field<Date> field4() {
        return UrlSnapshot.URL_SNAPSHOT.CRAWL_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUrl();
    }

    @Override
    public String component3() {
        return getScreenShotUrl();
    }

    @Override
    public Date component4() {
        return getCrawlTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUrl();
    }

    @Override
    public String value3() {
        return getScreenShotUrl();
    }

    @Override
    public Date value4() {
        return getCrawlTime();
    }

    @Override
    public UrlSnapshotRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UrlSnapshotRecord value2(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public UrlSnapshotRecord value3(String value) {
        setScreenShotUrl(value);
        return this;
    }

    @Override
    public UrlSnapshotRecord value4(Date value) {
        setCrawlTime(value);
        return this;
    }

    @Override
    public UrlSnapshotRecord values(Long value1, String value2, String value3, Date value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UrlSnapshotRecord
     */
    public UrlSnapshotRecord() {
        super(UrlSnapshot.URL_SNAPSHOT);
    }

    /**
     * Create a detached, initialised UrlSnapshotRecord
     */
    public UrlSnapshotRecord(Long id, String url, String screenShotUrl, Date crawlTime) {
        super(UrlSnapshot.URL_SNAPSHOT);

        setId(id);
        setUrl(url);
        setScreenShotUrl(screenShotUrl);
        setCrawlTime(crawlTime);
    }

    /**
     * Create a detached, initialised UrlSnapshotRecord
     */
    public UrlSnapshotRecord(com.tengzhe.jooq.data.naudit.tables.pojos.UrlSnapshot value) {
        super(UrlSnapshot.URL_SNAPSHOT);

        if (value != null) {
            setId(value.getId());
            setUrl(value.getUrl());
            setScreenShotUrl(value.getScreenShotUrl());
            setCrawlTime(value.getCrawlTime());
        }
    }
}
